# -*- coding: utf-8 -*-
"""
Série "Recuperação" — vídeos PÓS-OPERATÓRIOS para o PACIENTE (faceless, voz Antonio).
Diferente de "Pé no Chão"/"Osso Novo": registro em 2ª pessoa (fala direta com o paciente),
instrução clínica clara. Saída serve como Short do YouTube + link p/ enviar ao paciente.

═══ CONVENÇÕES DA SÉRIE (aprendizados consolidados — todo episódio novo SEGUE isto) ═══
 1. PAR ADULTO + INFANTIL: todo tema tem 2 episódios — adulto (fala com o paciente) e a "irmã"
    infantil (fala com os PAIS sobre "seu filho"). id infantil = "<tema>_kids".
 2. SINAIS DE ALARME → PRONTO-SOCORRO imediato, avisando a equipe NO CAMINHO (paralelo). NUNCA
    direcionar emergência ao WhatsApp. WhatsApp (11) 3280-1413 só p/ DÚVIDA DE ROTINA (cena de resumo).
 3. ALARME INFANTIL = os "3 A" pediátricos (Analgesia↑ / Ansiedade / Agitação) + dedos roxos/frios /
    não mexe — porque a criança pequena não localiza/descreve a dor (precede sinais clássicos).
 4. EDEMA: elevar o membro SEMPRE que em repouso, durante TODA a recuperação. SEM gelo sobre o gesso.
 5. CARGA: "varia conforme a cirurgia; em geral proibida no início — siga sua equipe" (nunca afirmar regra fixa).
 6. CFM (Res. 2.336/2023): educativo, sem prometer resultado, sem paciente real, rodapé CRM/RQE+disclaimer.
 7. PROCESSO: cada roteiro nasce de revisão de literatura com fontes e é APROVADO pelo Rafael (RQE)
    ANTES do render. Voz: edge Antonio, rate -8%, pitch -4Hz. Roteiros em projeto YouTube/videos_pos_operatorio/.
════════════════════════════════════════════════════════════════════════════════════════

Ep 01  — gesso_pos_op       — Cuidados com o gesso (adulto).
Ep 02  — gesso_pos_op_kids  — Cuidados com o gesso (criança / aos pais).
"""
POS_OP = [
 {"id":"gesso_pos_op","ep":1,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-operatório","sc":["Saiu de gesso","depois da cirurgia?"],"e":None,
    "sub":"Os cuidados que protegem o resultado — e os sinais de alarme.",
    "vo":"Você operou e saiu de gesso. Vou te mostrar os cuidados que protegem o resultado da sua cirurgia. E, no final, os sinais que pedem o pronto-socorro."},
   {"k":"Para desinchar","sc":["Em repouso,","mantenha elevado."],"e":"elevado",
    "sub":"Acima do coração — sempre que parar, durante toda a recuperação.",
    "vo":"Sempre que estiver parado, em repouso, deixe o braço ou a perna apoiada em travesseiros, acima da altura do coração. Faça isso durante toda a recuperação: é o que desincha e evita que volte a inchar."},
   {"k":"Circulação","sc":["Mexa sempre","os dedos."],"e":"dedos",
    "sub":"Movimentar os dedos livres ativa a circulação e evita rigidez.",
    "vo":"Movimente sempre os dedos que ficaram de fora do gesso. Isso mantém o sangue circulando e evita que eles enrijeçam."},
   {"k":"No banho","sc":["Mantenha o","gesso seco."],"e":"seco",
    "sub":"Capa impermeável é o mais seguro. Não cutuque por dentro.",
    "vo":"No banho, o jeito mais seguro de não molhar é uma capa impermeável. Saco plástico com toalha, bem vedado, quebra o galho, mas pode vazar. E nunca enfie nada pra coçar, nem tire o enchimento."},
   {"k":"Integridade","sc":["Molhou ou","rachou?"],"e":None,
    "sub":"Seque só com ar frio. Se perdeu a forma: pronto-socorro.",
    "vo":"Se molhar, seque só com ar frio. Ar quente queima a pele, que fica dormente embaixo do gesso. E se o gesso rachar, amolecer ou perder a forma, vá ao pronto-socorro pra trocar ou reforçar. Depois a equipe reavalia na sua consulta."},
   {"k":"Apoio de peso","sc":["Só pise quando","for liberado."],"e":"liberado",
    "sub":"Em geral é proibido no início — varia conforme a sua cirurgia.",
    "vo":"Sobre pisar: na maioria das vezes, o apoio do peso é proibido no começo. Mas isso muda conforme a sua cirurgia. Siga à risca o que a sua equipe orientou."},
   {"k":"Emergência","sc":["Pronto-socorro","se sentir:"],"e":None,"motif":"no",
    "sub":"Dor crescente · dormência · dedos roxos ou frios · gesso apertando.",
    "vo":"Agora, o mais importante. Vá ao pronto-socorro na hora se sentir: dor que aumenta e não passa com o remédio; formigamento ou dormência; dedos roxos, pálidos ou frios; inchaço muito forte; ou o gesso apertando cada vez mais. Avise a sua equipe no caminho, mas não espere: pode ser compressão da circulação, uma emergência."},
   {"k":"Resumo","sc":["Emergência?","Pronto-socorro."],"e":"Pronto-socorro",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: dúvida do dia a dia, fale com a nossa equipe no WhatsApp do consultório. Sinal de alarme, o caminho é o pronto-socorro. A sua recuperação é acompanhada de perto."},
  ],
  "caption":"Saiu de gesso depois da cirurgia? Os cuidados essenciais do pós-operatório — e os sinais que pedem PRONTO-SOCORRO imediato. Dúvidas de rotina fazem parte: fale com nossa equipe.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"gesso_pos_op_kids","ep":2,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-op infantil","sc":["Seu filho","saiu de gesso?"],"e":None,
    "sub":"Os cuidados — e os sinais que, numa criança, pedem pronto-socorro.",
    "vo":"Seu filho operou e saiu de gesso. Veja como cuidar nesses dias — e, principalmente, os sinais que, numa criança, pedem o pronto-socorro."},
   {"k":"Para desinchar","sc":["Em repouso,","deixe elevado."],"e":"elevado",
    "sub":"Acima do coração, sempre que parar — em toda a recuperação.",
    "vo":"Sempre que ele estiver parado, deitado no sofá ou na cama, apoie o bracinho ou a perna em travesseiros, acima da altura do coração. Faça isso a recuperação toda: desincha e evita que inche de novo."},
   {"k":"Circulação","sc":["Mexa os","dedinhos."],"e":"dedinhos",
    "sub":"Transforme em brincadeira — vira e mexe.",
    "vo":"Incentive a criança a mexer sempre os dedinhos que ficaram de fora. Vira brincadeira: mexe os dedos! Isso mantém o sangue circulando e evita que enrijeçam."},
   {"k":"No banho e no dia a dia","sc":["Nada entra","no gesso."],"e":None,
    "sub":"Capa impermeável · cubra a abertura · coceira: ar frio.",
    "vo":"No banho, proteja com uma capa impermeável e nunca mergulhe o gesso. E criança adora enfiar coisa lá dentro: cubra a abertura pra brinquedo, areia ou migalha não caírem. Se coçar, sopre ar frio com o secador, nunca um objeto."},
   {"k":"Integridade","sc":["Rachou ou","molhou?"],"e":None,
    "sub":"Perdeu a forma: pronto-socorro pra trocar ou reforçar.",
    "vo":"Criança bate o gesso o tempo todo. Se ele rachar, amolecer, molhar e não secar, ou perder a forma, leve ao pronto-socorro pra trocar ou reforçar. Depois a equipe reavalia na consulta."},
   {"k":"Apoio de peso","sc":["Só pisa se","liberado."],"e":"liberado",
    "sub":"Varia conforme a cirurgia — e exige supervisão.",
    "vo":"Sobre pôr o pé no chão: em geral é proibido no começo, mas varia conforme a cirurgia. Siga a orientação da equipe, e fique de olho, porque criança quer sair correndo."},
   {"k":"Emergência","sc":["Pronto-socorro","se notar:"],"e":None,"motif":"no",
    "sub":"Mais dor que antes · agitação · dedos roxos ou frios.",
    "vo":"Numa criança, o alarme mais importante é este: se ela passa a precisar de mais remédio pra dor do que antes, fica muito agitada, ansiosa ou chora sem parar. Some a isso dedos roxos, pálidos ou frios, ou que ela não mexe. Diante disso, pronto-socorro na hora, avisando a equipe no caminho. Pode ser compressão da circulação."},
   {"k":"Resumo","sc":["Emergência?","Pronto-socorro."],"e":"Pronto-socorro",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: dúvida do dia a dia, fale com a nossa equipe no WhatsApp. Sinal de alarme, o caminho é o pronto-socorro. A recuperação do seu filho é acompanhada de perto."},
  ],
  "caption":"Seu filho saiu de gesso depois da cirurgia? Os cuidados no dia a dia — e os sinais de alarme na criança (mais dor que antes, agitação, dedos roxos/frios) que pedem PRONTO-SOCORRO imediato.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"fixador_externo","ep":3,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-operatório","sc":["Você está com","fixador externo?"],"e":None,
    "sub":"Cuidar dos pinos evita a complicação mais comum: a infecção.",
    "vo":"Você saiu da cirurgia com um fixador externo: ele segura o osso por fora, com pinos que atravessam a pele. Cuidar bem desses pinos é o que evita a complicação mais comum, que é a infecção."},
   {"k":"No banho","sc":["Banho normal","está liberado."],"e":"liberado",
    "sub":"Lave os pinos no banho, com sabonete neutro.",
    "vo":"A boa notícia: o banho normal costuma ser liberado logo após a cirurgia. Aproveite pra limpar os pinos com sabonete neutro, do jeito que a sua equipe orientou."},
   {"k":"Secar e proteger","sc":["Seque bem.","Álcool só no metal."],"e":None,
    "sub":"Papel toalha ou secador no frio. Álcool no metal ao sair — nunca na pele.",
    "vo":"Depois, seque bem cada pino, com papel toalha ou secador no ar frio. Se for sair de casa, pode passar álcool só na parte de metal do fixador. Na pele, nunca."},
   {"k":"Mãos e materiais","sc":["Um material","por pino."],"e":"por pino","motif":"no",
    "sub":"Mãos limpas antes de tocar; ao secar, um papel para cada pino.",
    "vo":"Sempre com as mãos lavadas. E a regra de ouro: um material para cada pino. O papel que secou um pino não seca o outro — é assim que uma infecção pula de um ponto pro outro."},
   {"k":"Pode pisar","sc":["Em geral, carga","total liberada."],"e":"total",
    "sub":"O fixador foi feito para você se mover — confirme com sua equipe.",
    "vo":"E ao contrário do gesso, o fixador em geral permite apoiar o peso normalmente: ele foi feito pra você se mover. Mas confirme a liberação com a sua equipe, porque depende da sua cirurgia."},
   {"k":"Fique de olho","sc":["Vermelho, quente","ou com pus?"],"e":None,
    "sub":"Dor nova, calor, inchaço, secreção amarela ou cheiro, febre.",
    "vo":"Olhe os pinos todos os dias: dor ou sensibilidade que não havia, vermelhidão, calor, inchaço, secreção amarelada ou com cheiro, ou febre. Uma irritação leve é comum, mas precisa ser observada."},
   {"k":"Sinal de alarme","sc":["Procure o","pronto-socorro."],"e":None,"motif":"no",
    "sub":"Diante desses sinais, vá ao PS e avise sua equipe.",
    "vo":"Diante de qualquer um desses sinais, ou se piorar, procure o pronto-socorro e avise a sua equipe. Infecção de pino tratada cedo costuma se resolver bem."},
   {"k":"Resumo","sc":["Pinos limpos,","olho na infecção."],"e":"limpos",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: limpe no banho, seque bem, um material por pino, e olho nos sinais de infecção. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Está com fixador externo depois da cirurgia? O cuidado com os pinos (limpeza no banho com sabonete neutro, secar bem, álcool só no metal) — e os sinais de infecção que pedem o pronto-socorro. Em geral o fixador permite carga total: confirme com sua equipe.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"fixador_externo_kids","ep":4,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Fixador na criança","sc":["Seu filho está","com fixador?"],"e":None,
    "sub":"Cuidar dos pinos evita a infecção, a complicação mais comum.",
    "vo":"Seu filho saiu da cirurgia com um fixador externo: ele segura o osso por fora, com pinos na pele. Cuidar desses pinos é o que evita a complicação mais comum na criança, que é a infecção."},
   {"k":"No banho","sc":["Banho normal","está liberado."],"e":"liberado",
    "sub":"Lave os pinos no banho, com sabonete neutro.",
    "vo":"A boa notícia: o banho normal costuma ser liberado logo após a cirurgia. Aproveite pra limpar os pinos com sabonete neutro, do jeito que a equipe orientou."},
   {"k":"Secar e proteger","sc":["Seque bem.","Álcool só no metal."],"e":None,
    "sub":"Papel toalha ou secador no frio. Álcool no metal ao sair — nunca na pele.",
    "vo":"Depois seque bem cada pino, com papel toalha ou secador no ar frio. Para sair de casa, pode passar álcool só na parte de metal. Na pele da criança, nunca."},
   {"k":"Mãos, luva e materiais","sc":["Um material","por pino."],"e":"por pino","motif":"no",
    "sub":"Mãos lavadas e luva limpa; um papel para cada pino.",
    "vo":"Sempre com as mãos lavadas e uma luva limpa, que não precisa ser estéril. E a regra de ouro: um material para cada pino. O que secou um pino não toca o outro, nem a luva. É assim que a infecção pula de ponto."},
   {"k":"Pode pisar","sc":["Em geral, carga","total liberada."],"e":"total",
    "sub":"O fixador foi feito para a criança se mover — confirme com a equipe.",
    "vo":"E diferente do gesso, o fixador em geral deixa a criança apoiar o peso normalmente: ele foi feito pra ela se mover. Mas confirme a liberação com a equipe, porque depende da cirurgia."},
   {"k":"Fique de olho","sc":["Vermelho, quente","ou com pus?"],"e":None,
    "sub":"Dor nova, calor, inchaço, secreção amarela ou cheiro, febre ≥38°C.",
    "vo":"Olhe os pinos todos os dias: dor nova, vermelhidão, calor, inchaço, secreção amarela ou com cheiro, ou febre. Uma irritação leve é comum, mas precisa de acompanhamento."},
   {"k":"Sinal de alarme","sc":["Procure o","pronto-socorro."],"e":None,"motif":"no",
    "sub":"Diante desses sinais ou piora, leve ao PS e avise a equipe.",
    "vo":"Diante de qualquer um desses sinais, ou se a criança piorar ou ficar prostrada, leve ao pronto-socorro e avise a equipe. Tratada cedo, costuma se resolver bem."},
   {"k":"Resumo","sc":["Pinos limpos,","olho na infecção."],"e":"limpos",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: limpe no banho, seque bem, um material por pino, e olho nos sinais de infecção. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Seu filho está com fixador externo? O cuidado com os pinos (limpeza no banho com sabonete neutro, secar bem, álcool só no metal) — e os sinais de infecção que pedem o pronto-socorro. Em geral permite carga total: confirme com a equipe.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"carga_fisio","ep":5,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-operatório","sc":["Tem medo de","mexer depois?"],"e":None,
    "sub":"Mover cedo — quando liberado — é parte do tratamento.",
    "vo":"Muita gente sai da cirurgia com medo de mexer, achando que vai atrapalhar. Mas, no ritmo que a sua equipe liberar, o movimento é justamente parte do que cura."},
   {"k":"O mito do repouso","sc":["Ficar parado","não é o que cura."],"e":"parado",
    "sub":"Repouso demais perde força e enrijece a articulação.",
    "vo":"Ficar de molho o tempo todo não acelera nada. Pelo contrário: o músculo perde força e a articulação vai enrijecendo, e isso depois custa caro pra recuperar."},
   {"k":"Por que mexer","sc":["Movimento","reduz riscos."],"e":"reduz",
    "sub":"Menos rigidez, menos trombose, mais circulação.",
    "vo":"Mover cedo mantém a força, melhora a circulação e reduz o risco de trombose. É das coisas que mais protegem a sua recuperação."},
   {"k":"Carga","sc":["Apoiar o peso","estimula o osso."],"e":"estimula",
    "sub":"Quando seu cirurgião liberar — varia conforme a cirurgia.",
    "vo":"E pisar, quando o cirurgião liberar, não é só andar: a carga estimula o osso a consolidar. Mas o quanto e o quando dependem da sua cirurgia, então siga à risca a liberação."},
   {"k":"Fisioterapia","sc":["Fisioterapia","não é opcional."],"e":"não","motif":"no",
    "sub":"É parte do tratamento — começar cedo ganha amplitude.",
    "vo":"A fisioterapia não é um extra: é parte do tratamento. Começar no tempo certo é o que recupera a amplitude e a força, e evita aquela rigidez difícil de reverter."},
   {"k":"Com critério","sc":["No ritmo da","sua equipe."],"e":"ritmo",
    "sub":"Progressão lenta e qualidade de movimento protegem a cicatrização.",
    "vo":"Tudo com critério: quem dá o ritmo é a sua equipe. Progredir aos poucos, com movimento de qualidade, é o que protege a cicatrização."},
   {"k":"Não force","sc":["Dor ou inchaço","que pioram?"],"e":None,"motif":"no",
    "sub":"Não force; diante de sinal de alarme, pronto-socorro + avise a equipe.",
    "vo":"Agora, dor que aumenta muito ou inchaço que piora não é evoluir na marra: não force. E diante de sinais de alarme, procure o pronto-socorro e avise a equipe."},
   {"k":"Resumo","sc":["Mover cedo,","no ritmo certo."],"e":"cedo",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: mexer e apoiar cedo, no ritmo da sua equipe, é o que acelera de verdade. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Operou e tem medo de mexer? Mover e apoiar cedo — no ritmo que a sua equipe liberar — é parte do tratamento: reduz rigidez, trombose e perda de força. O repouso total não é o que cura. Fisioterapia é parte do tratamento.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"carga_fisio_kids","ep":6,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-op infantil","sc":["Medo de deixar","seu filho mexer?"],"e":None,
    "sub":"Movimento, no ritmo da equipe, é parte do tratamento.",
    "vo":"É natural querer proteger e deixar a criança paradinha depois da cirurgia. Mas, no ritmo que a equipe liberar, o movimento é parte do que cura."},
   {"k":"O mito do repouso","sc":["Criança parada","enrijece também."],"e":"parada",
    "sub":"Repouso demais perde força e amplitude.",
    "vo":"Criança também perde força e amplitude se fica parada demais. O corpo dela responde rápido ao movimento, pra o bem e pra o mal."},
   {"k":"Por que deixar mexer","sc":["Movimento","ajuda a curar."],"e":"ajuda",
    "sub":"Brincar dentro do limite mantém força e circulação.",
    "vo":"Dentro do que foi liberado, deixar a criança se mexer e brincar mantém a força, a circulação e a amplitude. Faz parte da recuperação."},
   {"k":"Carga","sc":["Pisar","conforme liberado."],"e":"conforme",
    "sub":"Varia conforme a cirurgia — siga a equipe e supervisione.",
    "vo":"Sobre pôr o pé no chão: o quanto e o quando dependem da cirurgia. Siga a liberação da equipe e fique por perto, porque criança quer testar os limites."},
   {"k":"Fisioterapia","sc":["Fisioterapia","não é opcional."],"e":"não","motif":"no",
    "sub":"Parte do tratamento; em criança, vira brincadeira guiada.",
    "vo":"A fisioterapia não é opcional: é parte do tratamento. Com a criança, ela costuma virar brincadeira guiada, e é o que recupera o movimento sem rigidez."},
   {"k":"Com critério","sc":["No ritmo da","equipe."],"e":"ritmo",
    "sub":"Progressão lenta protege a cicatrização.",
    "vo":"Tudo no ritmo da equipe. Aos poucos, com qualidade, protege a cicatrização, sem pressa de queimar etapas."},
   {"k":"Quando segurar","sc":["Dor ou inchaço","que pioram?"],"e":None,"motif":"no",
    "sub":"Não force; diante de sinal de alarme, pronto-socorro + avise a equipe.",
    "vo":"Se a criança tiver dor que aumenta muito, inchaço que piora, ou ficar muito prostrada, não force o movimento. E diante de sinais de alarme, pronto-socorro e avise a equipe."},
   {"k":"Resumo","sc":["Deixe mexer,","no ritmo certo."],"e":"mexer",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: deixar a criança se mover, no ritmo da equipe, é o que acelera. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Seu filho operou e você tem medo de deixar mexer? No ritmo que a equipe liberar, o movimento é parte do tratamento: reduz rigidez e perda de força. Fisioterapia, em criança, vira brincadeira guiada.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},
]
