# -*- coding: utf-8 -*-
"""
Série "Recuperação" — vídeos PÓS-OPERATÓRIOS para o PACIENTE (faceless, voz Antonio).
Diferente de "Pé no Chão"/"Osso Novo": registro em 2ª pessoa (fala direta com o paciente),
instrução clínica clara. Saída serve como Short do YouTube + link p/ enviar ao paciente.

═══ CONVENÇÕES DA SÉRIE (aprendizados consolidados — todo episódio novo SEGUE isto) ═══
 1. PAR ADULTO + INFANTIL: todo tema tem 2 episódios — adulto (fala com o paciente) e a "irmã"
    infantil (fala com os PAIS sobre "seu filho"). id infantil = "<tema>_kids".
 2. SINAIS DE ALARME → PRONTO-SOCORRO imediato, avisando a equipe NO CAMINHO (paralelo). NUNCA
    direcionar emergência ao WhatsApp. WhatsApp (11) 3280-1413 só p/ DÚVIDA DE ROTINA (cena de resumo).
 3. ALARME INFANTIL = os "3 A" pediátricos (Analgesia↑ / Ansiedade / Agitação) + dedos roxos/frios /
    não mexe — porque a criança pequena não localiza/descreve a dor (precede sinais clássicos).
 4. EDEMA: elevar o membro SEMPRE que em repouso, durante TODA a recuperação. SEM gelo sobre o gesso.
 5. CARGA: "varia conforme a cirurgia; em geral proibida no início — siga sua equipe" (nunca afirmar regra fixa).
 6. CFM (Res. 2.336/2023): educativo, sem prometer resultado, sem paciente real, rodapé CRM/RQE+disclaimer.
 7. PROCESSO: cada roteiro nasce de revisão de literatura com fontes e é APROVADO pelo Rafael (RQE)
    ANTES do render. Voz: edge Antonio, rate -8%, pitch -4Hz. Roteiros em projeto YouTube/videos_pos_operatorio/.
════════════════════════════════════════════════════════════════════════════════════════

Ep 01  — gesso_pos_op          — Cuidados com o gesso (adulto).
Ep 02  — gesso_pos_op_kids     — Cuidados com o gesso (criança / aos pais).
Ep 07  — artrorrise            — Pós-op artrorrise / pé plano (adulto).
Ep 08  — artrorrise_kids       — Pós-op artrorrise / pé plano (criança / aos pais).
Ep 09  — growth_guided         — Pós-op epifisiodese / guia de crescimento (adulto/adolescente).
Ep 10  — growth_guided_kids    — Pós-op epifisiodese / guia de crescimento (criança / aos pais).
Ep 11  — ferida_cirurgica      — Cuidados com a ferida e pontos (adulto).
Ep 12  — ferida_cirurgica_kids — Cuidados com a ferida e pontos (criança / aos pais).
Ep 13  — dor_posop             — Dor pós-op: normal × alarme (adulto).
Ep 14  — dor_posop_kids        — Dor pós-op: normal × alarme (criança / aos pais).
Ep 15  — edema                 — Inchaço/edema: por que e como manejar (adulto).
Ep 16  — edema_kids            — Inchaço/edema: por que e como manejar (criança / aos pais).
"""
POS_OP = [
 {"id":"gesso_pos_op","ep":1,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-operatório","sc":["Saiu de gesso","depois da cirurgia?"],"e":None,
    "sub":"Os cuidados que protegem o resultado — e os sinais de alarme.",
    "vo":"Você operou e saiu de gesso. Vou te mostrar os cuidados que protegem o resultado da sua cirurgia. E, no final, os sinais que pedem o pronto-socorro."},
   {"k":"Para desinchar","sc":["Em repouso,","mantenha elevado."],"e":"elevado",
    "sub":"Acima do coração — sempre que parar, durante toda a recuperação.",
    "vo":"Sempre que estiver parado, em repouso, deixe o braço ou a perna apoiada em travesseiros, acima da altura do coração. Faça isso durante toda a recuperação: é o que desincha e evita que volte a inchar."},
   {"k":"Circulação","sc":["Mexa sempre","os dedos."],"e":"dedos",
    "sub":"Movimentar os dedos livres ativa a circulação e evita rigidez.",
    "vo":"Movimente sempre os dedos que ficaram de fora do gesso. Isso mantém o sangue circulando e evita que eles enrijeçam."},
   {"k":"No banho","sc":["Mantenha o","gesso seco."],"e":"seco",
    "sub":"Capa impermeável é o mais seguro. Não cutuque por dentro.",
    "vo":"No banho, o jeito mais seguro de não molhar é uma capa impermeável. Saco plástico com toalha, bem vedado, quebra o galho, mas pode vazar. E nunca enfie nada pra coçar, nem tire o enchimento."},
   {"k":"Integridade","sc":["Molhou ou","rachou?"],"e":None,
    "sub":"Seque só com ar frio. Se perdeu a forma: pronto-socorro.",
    "vo":"Se molhar, seque só com ar frio. Ar quente queima a pele, que fica dormente embaixo do gesso. E se o gesso rachar, amolecer ou perder a forma, vá ao pronto-socorro pra trocar ou reforçar. Depois a equipe reavalia na sua consulta."},
   {"k":"Apoio de peso","sc":["Só pise quando","for liberado."],"e":"liberado",
    "sub":"Em geral é proibido no início — varia conforme a sua cirurgia.",
    "vo":"Sobre pisar: na maioria das vezes, o apoio do peso é proibido no começo. Mas isso muda conforme a sua cirurgia. Siga à risca o que a sua equipe orientou."},
   {"k":"Emergência","sc":["Pronto-socorro","se sentir:"],"e":None,"motif":"no",
    "sub":"Dor crescente · dormência · dedos roxos ou frios · gesso apertando.",
    "vo":"Agora, o mais importante. Vá ao pronto-socorro na hora se sentir: dor que aumenta e não passa com o remédio; formigamento ou dormência; dedos roxos, pálidos ou frios; inchaço muito forte; ou o gesso apertando cada vez mais. Avise a sua equipe no caminho, mas não espere: pode ser compressão da circulação, uma emergência."},
   {"k":"Resumo","sc":["Emergência?","Pronto-socorro."],"e":"Pronto-socorro",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: dúvida do dia a dia, fale com a nossa equipe no WhatsApp do consultório. Sinal de alarme, o caminho é o pronto-socorro. A sua recuperação é acompanhada de perto."},
  ],
  "caption":"Saiu de gesso depois da cirurgia? Os cuidados essenciais do pós-operatório — e os sinais que pedem PRONTO-SOCORRO imediato. Dúvidas de rotina fazem parte: fale com nossa equipe.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"gesso_pos_op_kids","ep":2,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-op infantil","sc":["Seu filho","saiu de gesso?"],"e":None,
    "sub":"Os cuidados — e os sinais que, numa criança, pedem pronto-socorro.",
    "vo":"Seu filho operou e saiu de gesso. Veja como cuidar nesses dias — e, principalmente, os sinais que, numa criança, pedem o pronto-socorro."},
   {"k":"Para desinchar","sc":["Em repouso,","deixe elevado."],"e":"elevado",
    "sub":"Acima do coração, sempre que parar — em toda a recuperação.",
    "vo":"Sempre que ele estiver parado, deitado no sofá ou na cama, apoie o bracinho ou a perna em travesseiros, acima da altura do coração. Faça isso a recuperação toda: desincha e evita que inche de novo."},
   {"k":"Circulação","sc":["Mexa os","dedinhos."],"e":"dedinhos",
    "sub":"Transforme em brincadeira — vira e mexe.",
    "vo":"Incentive a criança a mexer sempre os dedinhos que ficaram de fora. Vira brincadeira: mexe os dedos! Isso mantém o sangue circulando e evita que enrijeçam."},
   {"k":"No banho e no dia a dia","sc":["Nada entra","no gesso."],"e":None,
    "sub":"Capa impermeável · cubra a abertura · coceira: ar frio.",
    "vo":"No banho, proteja com uma capa impermeável e nunca mergulhe o gesso. E criança adora enfiar coisa lá dentro: cubra a abertura pra brinquedo, areia ou migalha não caírem. Se coçar, sopre ar frio com o secador, nunca um objeto."},
   {"k":"Integridade","sc":["Rachou ou","molhou?"],"e":None,
    "sub":"Perdeu a forma: pronto-socorro pra trocar ou reforçar.",
    "vo":"Criança bate o gesso o tempo todo. Se ele rachar, amolecer, molhar e não secar, ou perder a forma, leve ao pronto-socorro pra trocar ou reforçar. Depois a equipe reavalia na consulta."},
   {"k":"Apoio de peso","sc":["Só pisa se","liberado."],"e":"liberado",
    "sub":"Varia conforme a cirurgia — e exige supervisão.",
    "vo":"Sobre pôr o pé no chão: em geral é proibido no começo, mas varia conforme a cirurgia. Siga a orientação da equipe, e fique de olho, porque criança quer sair correndo."},
   {"k":"Emergência","sc":["Pronto-socorro","se notar:"],"e":None,"motif":"no",
    "sub":"Mais dor que antes · agitação · dedos roxos ou frios.",
    "vo":"Numa criança, o alarme mais importante é este: se ela passa a precisar de mais remédio pra dor do que antes, fica muito agitada, ansiosa ou chora sem parar. Some a isso dedos roxos, pálidos ou frios, ou que ela não mexe. Diante disso, pronto-socorro na hora, avisando a equipe no caminho. Pode ser compressão da circulação."},
   {"k":"Resumo","sc":["Emergência?","Pronto-socorro."],"e":"Pronto-socorro",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: dúvida do dia a dia, fale com a nossa equipe no WhatsApp. Sinal de alarme, o caminho é o pronto-socorro. A recuperação do seu filho é acompanhada de perto."},
  ],
  "caption":"Seu filho saiu de gesso depois da cirurgia? Os cuidados no dia a dia — e os sinais de alarme na criança (mais dor que antes, agitação, dedos roxos/frios) que pedem PRONTO-SOCORRO imediato.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"fixador_externo","ep":3,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-operatório","sc":["Você está com","fixador externo?"],"e":None,
    "sub":"Cuidar dos pinos evita a complicação mais comum: a infecção.",
    "vo":"Você saiu da cirurgia com um fixador externo: ele segura o osso por fora, com pinos que atravessam a pele. Cuidar bem desses pinos é o que evita a complicação mais comum, que é a infecção."},
   {"k":"No banho","sc":["Banho normal","está liberado."],"e":"liberado",
    "sub":"Lave os pinos no banho, com sabonete neutro.",
    "vo":"A boa notícia: o banho normal costuma ser liberado logo após a cirurgia. Aproveite pra limpar os pinos com sabonete neutro, do jeito que a sua equipe orientou."},
   {"k":"Secar e proteger","sc":["Seque bem.","Álcool só no metal."],"e":None,
    "sub":"Papel toalha ou secador no frio. Álcool no metal ao sair — nunca na pele.",
    "vo":"Depois, seque bem cada pino, com papel toalha ou secador no ar frio. Se for sair de casa, pode passar álcool só na parte de metal do fixador. Na pele, nunca."},
   {"k":"Mãos e materiais","sc":["Um material","por pino."],"e":"por pino","motif":"no",
    "sub":"Mãos limpas antes de tocar; ao secar, um papel para cada pino.",
    "vo":"Sempre com as mãos lavadas. E a regra de ouro: um material para cada pino. O papel que secou um pino não seca o outro — é assim que uma infecção pula de um ponto pro outro."},
   {"k":"Pode pisar","sc":["Em geral, carga","total liberada."],"e":"total",
    "sub":"O fixador foi feito para você se mover — confirme com sua equipe.",
    "vo":"E ao contrário do gesso, o fixador em geral permite apoiar o peso normalmente: ele foi feito pra você se mover. Mas confirme a liberação com a sua equipe, porque depende da sua cirurgia."},
   {"k":"Fique de olho","sc":["Vermelho, quente","ou com pus?"],"e":None,
    "sub":"Dor nova, calor, inchaço, secreção amarela ou cheiro, febre.",
    "vo":"Olhe os pinos todos os dias: dor ou sensibilidade que não havia, vermelhidão, calor, inchaço, secreção amarelada ou com cheiro, ou febre. Uma irritação leve é comum, mas precisa ser observada."},
   {"k":"Sinal de alarme","sc":["Procure o","pronto-socorro."],"e":None,"motif":"no",
    "sub":"Diante desses sinais, vá ao PS e avise sua equipe.",
    "vo":"Diante de qualquer um desses sinais, ou se piorar, procure o pronto-socorro e avise a sua equipe. Infecção de pino tratada cedo costuma se resolver bem."},
   {"k":"Resumo","sc":["Pinos limpos,","olho na infecção."],"e":"limpos",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: limpe no banho, seque bem, um material por pino, e olho nos sinais de infecção. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Está com fixador externo depois da cirurgia? O cuidado com os pinos (limpeza no banho com sabonete neutro, secar bem, álcool só no metal) — e os sinais de infecção que pedem o pronto-socorro. Em geral o fixador permite carga total: confirme com sua equipe.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"fixador_externo_kids","ep":4,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Fixador na criança","sc":["Seu filho está","com fixador?"],"e":None,
    "sub":"Cuidar dos pinos evita a infecção, a complicação mais comum.",
    "vo":"Seu filho saiu da cirurgia com um fixador externo: ele segura o osso por fora, com pinos na pele. Cuidar desses pinos é o que evita a complicação mais comum na criança, que é a infecção."},
   {"k":"No banho","sc":["Banho normal","está liberado."],"e":"liberado",
    "sub":"Lave os pinos no banho, com sabonete neutro.",
    "vo":"A boa notícia: o banho normal costuma ser liberado logo após a cirurgia. Aproveite pra limpar os pinos com sabonete neutro, do jeito que a equipe orientou."},
   {"k":"Secar e proteger","sc":["Seque bem.","Álcool só no metal."],"e":None,
    "sub":"Papel toalha ou secador no frio. Álcool no metal ao sair — nunca na pele.",
    "vo":"Depois seque bem cada pino, com papel toalha ou secador no ar frio. Para sair de casa, pode passar álcool só na parte de metal. Na pele da criança, nunca."},
   {"k":"Mãos, luva e materiais","sc":["Um material","por pino."],"e":"por pino","motif":"no",
    "sub":"Mãos lavadas e luva limpa; um papel para cada pino.",
    "vo":"Sempre com as mãos lavadas e uma luva limpa, que não precisa ser estéril. E a regra de ouro: um material para cada pino. O que secou um pino não toca o outro, nem a luva. É assim que a infecção pula de ponto."},
   {"k":"Pode pisar","sc":["Em geral, carga","total liberada."],"e":"total",
    "sub":"O fixador foi feito para a criança se mover — confirme com a equipe.",
    "vo":"E diferente do gesso, o fixador em geral deixa a criança apoiar o peso normalmente: ele foi feito pra ela se mover. Mas confirme a liberação com a equipe, porque depende da cirurgia."},
   {"k":"Fique de olho","sc":["Vermelho, quente","ou com pus?"],"e":None,
    "sub":"Dor nova, calor, inchaço, secreção amarela ou cheiro, febre ≥38°C.",
    "vo":"Olhe os pinos todos os dias: dor nova, vermelhidão, calor, inchaço, secreção amarela ou com cheiro, ou febre. Uma irritação leve é comum, mas precisa de acompanhamento."},
   {"k":"Sinal de alarme","sc":["Procure o","pronto-socorro."],"e":None,"motif":"no",
    "sub":"Diante desses sinais ou piora, leve ao PS e avise a equipe.",
    "vo":"Diante de qualquer um desses sinais, ou se a criança piorar ou ficar prostrada, leve ao pronto-socorro e avise a equipe. Tratada cedo, costuma se resolver bem."},
   {"k":"Resumo","sc":["Pinos limpos,","olho na infecção."],"e":"limpos",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: limpe no banho, seque bem, um material por pino, e olho nos sinais de infecção. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Seu filho está com fixador externo? O cuidado com os pinos (limpeza no banho com sabonete neutro, secar bem, álcool só no metal) — e os sinais de infecção que pedem o pronto-socorro. Em geral permite carga total: confirme com a equipe.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"carga_fisio","ep":5,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-operatório","sc":["Tem medo de","mexer depois?"],"e":None,
    "sub":"Mover cedo — quando liberado — é parte do tratamento.",
    "vo":"Muita gente sai da cirurgia com medo de mexer, achando que vai atrapalhar. Mas, no ritmo que a sua equipe liberar, o movimento é justamente parte da sua recuperação."},
   {"k":"O mito do repouso","sc":["Ficar parado","não é o que cura."],"e":"parado",
    "sub":"Repouso demais perde força e enrijece a articulação.",
    "vo":"Ficar de molho o tempo todo não acelera nada. Pelo contrário: o músculo perde força e a articulação vai enrijecendo, e isso depois custa caro pra recuperar."},
   {"k":"Por que mexer","sc":["Movimento","reduz riscos."],"e":"reduz",
    "sub":"Menos rigidez, menos trombose, mais circulação.",
    "vo":"Mover cedo mantém a força, melhora a circulação e reduz o risco de trombose. É das coisas que mais protegem a sua recuperação."},
   {"k":"Carga","sc":["Apoiar o peso","estimula o osso."],"e":"estimula",
    "sub":"Quando seu cirurgião liberar — varia conforme a cirurgia.",
    "vo":"E pisar, quando o cirurgião liberar, não é só andar: a carga estimula o osso a consolidar. Mas o quanto e o quando dependem da sua cirurgia, então siga à risca a liberação."},
   {"k":"Fisioterapia","sc":["Fisioterapia","não é opcional."],"e":"não","motif":"no",
    "sub":"É parte do tratamento — começar cedo ganha amplitude.",
    "vo":"A fisioterapia não é um extra: é parte do tratamento. Começar no tempo certo é o que recupera a amplitude e a força, e evita aquela rigidez difícil de reverter."},
   {"k":"Com critério","sc":["No ritmo da","sua equipe."],"e":"ritmo",
    "sub":"Progressão lenta e qualidade de movimento protegem a cicatrização.",
    "vo":"Tudo com critério: quem dá o ritmo é a sua equipe. Progredir aos poucos, com movimento de qualidade, é o que protege a cicatrização."},
   {"k":"Não force","sc":["Dor ou inchaço","que pioram?"],"e":None,"motif":"no",
    "sub":"Não force; diante de sinal de alarme, pronto-socorro + avise a equipe.",
    "vo":"Agora, dor que aumenta muito ou inchaço que piora não é evoluir na marra: não force. E diante de sinais de alarme, procure o pronto-socorro e avise a equipe."},
   {"k":"Resumo","sc":["Mover cedo,","no ritmo certo."],"e":"cedo",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: mexer e apoiar cedo, no ritmo da sua equipe, é o que acelera de verdade. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Operou e tem medo de mexer? Mover e apoiar cedo — no ritmo que a sua equipe liberar — é parte do tratamento: reduz rigidez, trombose e perda de força. O repouso total não é o que acelera. Fisioterapia é parte do tratamento.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"carga_fisio_kids","ep":6,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "scenes":[
   {"k":"Pós-op infantil","sc":["Medo de deixar","seu filho mexer?"],"e":None,
    "sub":"Movimento, no ritmo da equipe, é parte do tratamento.",
    "vo":"É natural querer proteger e deixar a criança paradinha depois da cirurgia. Mas, no ritmo que a equipe liberar, o movimento é parte da recuperação dela."},
   {"k":"O mito do repouso","sc":["Criança parada","enrijece também."],"e":"parada",
    "sub":"Repouso demais perde força e amplitude.",
    "vo":"Criança também perde força e amplitude se fica parada demais. O corpo dela responde rápido ao movimento, pra o bem e pra o mal."},
   {"k":"Por que deixar mexer","sc":["Movimento","ajuda a curar."],"e":"ajuda",
    "sub":"Brincar dentro do limite mantém força e circulação.",
    "vo":"Dentro do que foi liberado, deixar a criança se mexer e brincar mantém a força, a circulação e a amplitude. Faz parte da recuperação."},
   {"k":"Carga","sc":["Pisar","conforme liberado."],"e":"conforme",
    "sub":"Varia conforme a cirurgia — siga a equipe e supervisione.",
    "vo":"Sobre pôr o pé no chão: o quanto e o quando dependem da cirurgia. Siga a liberação da equipe e fique por perto, porque criança quer testar os limites."},
   {"k":"Fisioterapia","sc":["Fisioterapia","não é opcional."],"e":"não","motif":"no",
    "sub":"Parte do tratamento; em criança, vira brincadeira guiada.",
    "vo":"A fisioterapia não é opcional: é parte do tratamento. Com a criança, ela costuma virar brincadeira guiada, e é o que recupera o movimento sem rigidez."},
   {"k":"Com critério","sc":["No ritmo da","equipe."],"e":"ritmo",
    "sub":"Progressão lenta protege a cicatrização.",
    "vo":"Tudo no ritmo da equipe. Aos poucos, com qualidade, protege a cicatrização, sem pressa de queimar etapas."},
   {"k":"Quando segurar","sc":["Dor ou inchaço","que pioram?"],"e":None,"motif":"no",
    "sub":"Não force; diante de sinal de alarme, pronto-socorro + avise a equipe.",
    "vo":"Se a criança tiver dor que aumenta muito, inchaço que piora, ou ficar muito prostrada, não force o movimento. E diante de sinais de alarme, pronto-socorro e avise a equipe."},
   {"k":"Resumo","sc":["Deixe mexer,","no ritmo certo."],"e":"mexer",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: deixar a criança se mover, no ritmo da equipe, é o que acelera. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Seu filho operou e você tem medo de deixar mexer? No ritmo que a equipe liberar, o movimento é parte do tratamento: reduz rigidez e perda de força. Fisioterapia, em criança, vira brincadeira guiada.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 # ── ④ Artrorrise / pé plano ──────────────────────────────────────────────────────────
 # Arquétipo gancho: micro_caso (adulto) · pergunta (kids). Palette: noturno_azul / verde_clinico.
 # Fontes: SBOT; Gutteck et al., JBJS 2019; consenso pós-op de Ilizarov/artrorrise do serviço.
 {"id":"artrorrise","ep":7,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"noturno_azul",
  "scenes":[
   {"k":"SAIU DA CIRURGIA","sc":["Um implante minúsculo,","grande diferença."],"e":None,
    "sub":"A artrorrise corrigiu o pé plano — e os primeiros dias em casa definem o resultado.",
    "vo":"Você passou pela artrorrise: um implante pequeníssimo entrou no calcanhar pra corrigir o pé plano. O resultado de longo prazo começa nesses primeiros dias em casa."},
   {"k":"Para desinchar","sc":["Em repouso,","pé elevado."],"e":"elevado",
    "sub":"Travesseiro abaixo do pé, acima do coração — em toda a recuperação.",
    "vo":"Sempre que parar, eleve o pé com um travesseiro, acima da altura do coração. Faz isso durante toda a recuperação: é o que controla o inchaço."},
   {"k":"A bota","sc":["Não tire","por conta própria."],"e":"Não tire",
    "sub":"Ela protege o implante enquanto o corpo se adapta.",
    "vo":"A bota ou imobilização mantém o pé na posição certa enquanto o corpo se adapta ao implante. Não tire por conta própria — siga exatamente o que a equipe orientou."},
   {"k":"Apoio de peso","sc":["No ritmo","da liberação."],"e":"liberação",
    "sub":"Varia conforme a cirurgia — siga sua equipe.",
    "vo":"Pisar vai sendo liberado aos poucos, conforme a cicatrização avança. O ritmo e o quanto dependem da sua cirurgia — siga à risca a orientação da equipe."},
   {"k":"A ferida","sc":["Seca,","limpa e coberta."],"e":"Seca",
    "sub":"No banho, proteja conforme orientado; curativo sujo — troque e avise.",
    "vo":"Mantenha a ferida limpa, seca e coberta. No banho, proteja conforme a equipe orientou. Se o curativo sujar ou soltar, troque e avise."},
   {"k":"Fique de olho","sc":["Dor crescente,","vermelho ou febre?"],"e":None,
    "sub":"Inchaço que não cede · calor · ferida com secreção.",
    "vo":"Olhe o pé todo dia: dor que vai aumentando, vermelhidão, calor, inchaço que não reduz, ferida com secreção ou febre. Qualquer um merece atenção."},
   {"k":"Sinal de alarme","sc":["Pronto-socorro","se tiver:"],"e":None,"motif":"no",
    "sub":"Dor intensa · dedos roxos ou frios · febre · ferida com pus.",
    "vo":"Diante de dor intensa que não cede, dedos roxos ou frios, febre, ou ferida com pus, vá ao pronto-socorro e avise a equipe. Não espere."},
   {"k":"Resumo","sc":["Elevação,","pronto-socorro."],"e":"Elevação",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: pé elevado no repouso, bota como orientado, e pronto-socorro se vier qualquer sinal de alarme. Dúvida do dia a dia, fale com a nossa equipe no WhatsApp."},
  ],
  "caption":"Fez artrorrise (implante pra pé plano) e está em casa? Elevação no repouso, bota como orientado, ferida seca — e pronto-socorro imediato se dor intensa, dedos roxos/frios ou febre.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"artrorrise_kids","ep":8,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"verde_clinico",
  "scenes":[
   {"k":"VOCÊ SABIA?","sc":["A artrorrise","corrige o pé plano?"],"e":"artrorrise",
    "sub":"E os primeiros dias em casa decidem o resultado do seu filho.",
    "vo":"Sabia que a artrorrise corrige o pé plano com um implante pequeníssimo, sem uma grande cirurgia? Os cuidados em casa não são complicados — mas têm detalhes que protegem o resultado do seu filho."},
   {"k":"Para desinchar","sc":["Em repouso,","pé elevado."],"e":"elevado",
    "sub":"Acima do coração — sempre que parar, a recuperação toda.",
    "vo":"Sempre que seu filho parar, eleve o pé com um travesseiro, acima da altura do coração. Faz isso durante toda a recuperação: é o que controla o inchaço, normal após a artrorrise."},
   {"k":"A bota","sc":["Não tire","por conta própria."],"e":"Não tire",
    "sub":"Protege o implante enquanto o corpo se adapta — e define quando pode pisar.",
    "vo":"A bota protege o implante enquanto o pé do seu filho se adapta. Não tire por conta própria e siga as orientações da equipe — especialmente sobre quando ele pode apoiar o pé no chão."},
   {"k":"Apoio de peso","sc":["No ritmo","da equipe."],"e":"ritmo",
    "sub":"Varia conforme a cirurgia — siga e supervisione.",
    "vo":"O quanto pode pisar vai sendo liberado aos poucos, e depende da cirurgia. Siga à risca e supervisione, porque criança quer testar os limites."},
   {"k":"A ferida","sc":["Seca,","limpa e coberta."],"e":"Seca",
    "sub":"Proteja no banho conforme orientado; curativo sujo — troque e avise.",
    "vo":"Mantenha a ferida limpa, seca e coberta. No banho, proteja conforme a equipe orientou. Se o curativo sujar ou soltar, troque e avise."},
   {"k":"Fique de olho","sc":["Dor crescente,","ou febre?"],"e":None,
    "sub":"Inchaço que não cede · vermelhidão · calor · ferida com secreção.",
    "vo":"Olhe o pé todo dia: dor que vai aumentando, vermelhidão, calor, inchaço que não reduz, ferida com secreção ou febre. Qualquer um merece atenção."},
   {"k":"Sinal de alarme","sc":["Mais dor,","dedos roxos?"],"e":None,"motif":"no",
    "sub":"3 As: Analgesia↑ · Ansiedade · Agitação + dedos roxos ou frios.",
    "vo":"Na criança, fique atento: se precisar de mais remédio pra dor do que antes, ficar muito agitada ou ansiosa — são os primeiros sinais. Some a isso dedos roxos ou frios. Pronto-socorro na hora e avise a equipe no caminho."},
   {"k":"Resumo","sc":["Elevação,","pronto-socorro."],"e":"Elevação",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: pé elevado no repouso, bota como orientado, olho nos sinais — pronto-socorro se precisar. Dúvida do dia a dia, fale com a gente."},
  ],
  "caption":"Seu filho fez artrorrise (implante pra pé plano) e está em casa? Elevação no repouso, bota como orientado, ferida seca — e pronto-socorro imediato se mais dor que antes, agitação, dedos roxos/frios.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 # ── ⑤ Epifisiodese / Growth Guided ──────────────────────────────────────────────────
 # Arquétipo gancho: alerta (adolescente/adulto) · mito_vs_verdade (kids).
 # Palette: carvao_quente / noturno_azul.
 # Fontes: SBOT; Sabharwal S., JBJS 2015 (guided growth); Paley D. protocols.
 # Clínica: freia placa de crescimento com implante (8-plate/staple) → corrige dismetria ou
 # deformidade angular; implante removível quando corrigido; baixa morbidade, cirurgia curta.
 {"id":"growth_guided","ep":9,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"carvao_quente",
  "scenes":[
   {"k":"ATENÇÃO","sc":["Operou o","crescimento?"],"e":"crescimento",
    "sub":"A epifisiodese age aos poucos — mas os primeiros cuidados importam muito.",
    "vo":"Se você operou a placa de crescimento — a epifisiodese — a cirurgia parece simples, mas o que acontece em casa nos primeiros dias define muito da recuperação."},
   {"k":"Para desinchar","sc":["Em repouso,","membro elevado."],"e":"elevado",
    "sub":"Acima do coração — sempre que parar, durante toda a recuperação.",
    "vo":"Sempre que parar, eleve o membro operado com um travesseiro, acima da altura do coração. Faz isso durante toda a recuperação: controla o inchaço, que é normal depois da cirurgia."},
   {"k":"A ferida","sc":["Seca,","limpa e coberta."],"e":"Seca",
    "sub":"No banho, proteja conforme orientado; curativo sujo — troque e avise.",
    "vo":"Mantenha a ferida limpa, seca e coberta. No banho, proteja conforme a equipe orientou. Se o curativo sujar ou soltar, troque e avise."},
   {"k":"Apoio de peso","sc":["Em geral","liberado logo."],"e":"liberado",
    "sub":"A epifisiodese costuma permitir carga cedo — confirme com sua equipe.",
    "vo":"A boa notícia: a epifisiodese em geral permite apoiar o peso logo após a cirurgia. Mas o quanto e o quando dependem da sua operação específica — confirme com a equipe."},
   {"k":"O implante","sc":["Vai ser retirado","depois."],"e":None,
    "sub":"Quando a correção estiver pronta, o implante é removido — planejado.",
    "vo":"O implante — a plaquinha ou grampo — vai ser retirado quando a correção atingir o objetivo. Isso é parte do plano desde o começo; a equipe vai acompanhar o crescimento em consultas regulares."},
   {"k":"Fique de olho","sc":["Dor crescente,","vermelho ou febre?"],"e":None,
    "sub":"Inchaço que não cede · calor · ferida com secreção.",
    "vo":"Olhe a ferida todo dia: dor que vai aumentando, vermelhidão, calor, inchaço que não reduz, secreção ou febre. Uma irritação leve é normal nas primeiras 48h; após isso, atenção."},
   {"k":"Sinal de alarme","sc":["Pronto-socorro","se tiver:"],"e":None,"motif":"no",
    "sub":"Dor intensa · febre alta · ferida com pus · membro muito inchado.",
    "vo":"Diante de dor intensa que não cede, febre alta, ferida com pus, ou membro muito inchado, vá ao pronto-socorro e avise a equipe. Não espere pela consulta."},
   {"k":"Resumo","sc":["Elevação,","consultas em dia."],"e":"Elevação",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: membro elevado no repouso, ferida seca, acompanhe as consultas — é o ritmo de crescimento que guia o tratamento. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Fez epifisiodese (cirurgia de guia de crescimento) e está em casa? Elevação no repouso, ferida seca, carga conforme liberado — e pronto-socorro se dor intensa, febre ou pus. O implante será retirado quando a correção estiver pronta.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"growth_guided_kids","ep":10,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"noturno_azul",
  "scenes":[
   {"k":"MITO OU VERDADE?","sc":["A cirurgia parou","o crescimento?"],"e":"parou",
    "sub":"Mito — a epifisiodese freia, corrige e depois o crescimento volta.",
    "vo":"Muita família acha que a epifisiodese parou o crescimento do filho para sempre. Isso é um mito. Ela freia temporariamente a placa certa para corrigir a diferença — e depois, com o implante retirado, o crescimento continua."},
   {"k":"Para desinchar","sc":["Em repouso,","membro elevado."],"e":"elevado",
    "sub":"Travesseiro abaixo do membro, acima do coração — a recuperação toda.",
    "vo":"Sempre que seu filho parar, eleve o membro operado acima da altura do coração. Faz isso durante toda a recuperação: é o que controla o inchaço."},
   {"k":"A ferida","sc":["Seca,","limpa e coberta."],"e":"Seca",
    "sub":"Proteja no banho conforme orientado; curativo sujo — troque e avise.",
    "vo":"Mantenha a ferida limpa, seca e coberta. No banho, proteja conforme a equipe orientou. Se o curativo sujar ou soltar, troque e avise."},
   {"k":"Apoio de peso","sc":["Em geral","liberado cedo."],"e":"liberado",
    "sub":"A epifisiodese costuma permitir carga logo — confirme e supervisione.",
    "vo":"A boa notícia: a cirurgia em geral permite pôr o pé no chão logo. O quanto e o quando dependem da cirurgia do seu filho — confirme com a equipe e supervisione, porque criança quer correr."},
   {"k":"O implante","sc":["Vai sair","quando pronto."],"e":None,
    "sub":"Quando a correção atingir o objetivo, o implante é retirado.",
    "vo":"O implante — a plaquinha ou grampo — vai ser retirado quando a correção atingir o objetivo. Isso é parte do plano desde o começo. As consultas de acompanhamento são essenciais: é o crescimento do seu filho que dita o ritmo."},
   {"k":"Fique de olho","sc":["Dor crescente,","ou febre?"],"e":None,
    "sub":"Inchaço que não cede · vermelhidão · calor · ferida com secreção.",
    "vo":"Olhe a ferida todo dia: dor que vai aumentando, vermelhidão, calor, inchaço que não reduz, secreção ou febre. Atenção especial após as primeiras 48h."},
   {"k":"Sinal de alarme","sc":["Mais dor,","febre ou pus?"],"e":None,"motif":"no",
    "sub":"3 As: Analgesia↑ · Ansiedade · Agitação + febre ou ferida com pus.",
    "vo":"Na criança, fique atento: se ela precisar de mais remédio pra dor do que antes, ficar muito agitada ou ansiosa — são os primeiros sinais. Some a isso febre ou ferida com pus: pronto-socorro na hora e avise a equipe."},
   {"k":"Resumo","sc":["Elevação,","consultas em dia."],"e":"Elevação",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: membro elevado no repouso, ferida seca, não pule as consultas — é o crescimento do seu filho que guia o tratamento. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Seu filho fez epifisiodese (cirurgia de guia de crescimento)? O implante freia temporariamente — não para o crescimento. Elevação no repouso, ferida seca, carga conforme liberado — pronto-socorro se mais dor, agitação, febre ou pus.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 # ── ⑥ Ferida cirúrgica e pontos ─────────────────────────────────────────────────────
 # Arquétipo gancho: boa_noticia (adulto) · dado_estatistica (kids). Palette: verde_clinico / carvao_quente.
 # Fontes: SBOT; UpToDate Postoperative wound care; CDC Surgical Site Infection guidelines.
 {"id":"ferida_cirurgica","ep":11,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"verde_clinico",
  "scenes":[
   {"k":"BOA NOTÍCIA","sc":["A ferida","fecha bem."],"e":"fecha",
    "sub":"Com os cuidados certos — e atenção aos sinais de alarme.",
    "vo":"Boa notícia: a ferida cirúrgica fecha bem na grande maioria das vezes. O que você faz em casa nos primeiros dias é o que protege esse resultado."},
   {"k":"O curativo","sc":["Troque como","orientado."],"e":None,
    "sub":"Em geral 1x/dia ou quando sujar/molhar — siga a instrução da equipe.",
    "vo":"Troque o curativo como a sua equipe orientou — em geral uma vez por dia, ou quando sujar ou molhar. Mãos lavadas sempre antes de tocar."},
   {"k":"Molhar","sc":["Aguarde a","liberação."],"e":"liberação",
    "sub":"Em geral 48–72h; depois água e sabão suave no banho — sem esfregar.",
    "vo":"A maioria das equipes libera molhar levemente após 48 a 72 horas. Depois, água e sabão suave no banho, sem esfregar. Siga o que a sua equipe orientou, porque depende do tipo de cirurgia."},
   {"k":"Não mexa","sc":["Não arranhe,","não esprema."],"e":None,"motif":"no",
    "sub":"Coceira = cicatrização ativa. Pressione levemente se precisar — nunca cutuque.",
    "vo":"Se coçar, é sinal de que está cicatrizando. Pressione levemente com o dedo limpo se incomodar. Mas nunca cutuque, esprema nem tire crostas — isso abre a porta para infecção."},
   {"k":"Cicatriz normal","sc":["Vermelhidão leve","nas bordas."],"e":None,
    "sub":"Primeiras semanas: bordas avermelhadas e endurecidas são inflamação normal.",
    "vo":"Nas primeiras semanas, as bordas da ferida ficam levemente avermelhadas e um pouco endurecidas. Isso é inflamação normal, parte da cicatrização."},
   {"k":"Fique de olho","sc":["Vermelhidão","que alastra?"],"e":None,
    "sub":"Vermelhidão crescente · calor · secreção · bordas abertas · febre.",
    "vo":"Olhe a ferida todo dia: vermelhidão que vai aumentando além das bordas, calor, secreção amarela ou com cheiro, bordas que se abriram, ou febre. São sinais de que algo não vai bem."},
   {"k":"Sinal de alarme","sc":["Pronto-socorro","se tiver:"],"e":None,"motif":"no",
    "sub":"Ferida aberta · pus · febre · vermelhidão que alastra rapidamente.",
    "vo":"Diante de ferida que abriu, pus, febre, ou vermelhidão que está avançando rápido na pele ao redor, vá ao pronto-socorro e avise a equipe. Infecção tratada cedo se resolve bem."},
   {"k":"Resumo","sc":["Curativo seco,","olho na ferida."],"e":"seco",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: curativo seco e limpo, sem melar nem cutucar, e olho nos sinais todos os dias. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Operou e está em casa com a ferida? Curativo seco, sem arranhar, sem molhar antes da liberação — e olho em vermelhidão crescente, pus, ferida aberta ou febre: esses sinais pedem pronto-socorro.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"ferida_cirurgica_kids","ep":12,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"carvao_quente",
  "scenes":[
   {"k":"SABIA QUE...","sc":["A maioria das","complicações é evitável."],"e":"evitável",
    "sub":"Com cuidados simples em casa, a ferida do seu filho fecha sem problema.",
    "vo":"A maioria das complicações de ferida cirúrgica em criança é evitável — com cuidados simples que você faz em casa. Vou te mostrar o que fazer e o que observar."},
   {"k":"O curativo","sc":["Troque como","orientado."],"e":None,
    "sub":"Em geral 1x/dia ou quando sujar/molhar — mãos lavadas antes.",
    "vo":"Troque o curativo como a equipe orientou, em geral uma vez por dia ou quando sujar ou molhar. Sempre com as mãos lavadas — e distância da criança pra não tocar na ferida com as mãos sujas."},
   {"k":"Molhar","sc":["Aguarde a","liberação."],"e":"liberação",
    "sub":"Em geral 48–72h; depois água e sabão suave — sem esfregar.",
    "vo":"Em geral, molhar levemente é liberado após 48 a 72 horas. Depois, água e sabão suave no banho, sem esfregar a ferida. Siga o que a equipe orientou para a cirurgia específica do seu filho."},
   {"k":"Não deixe mexer","sc":["Criança mexa","na ferida?"],"e":None,"motif":"no",
    "sub":"Distração é o melhor aliado. Cobrir com curativo atraente ajuda.",
    "vo":"Criança tem curiosidade — quer olhar, tocar, tirar curativo. Distração é o melhor aliado. Mantenha o curativo firme, e se a criança for mais velha, explique por que não pode mexer."},
   {"k":"Cicatriz normal","sc":["Bordas levemente","vermelhas."],"e":None,
    "sub":"Primeiras semanas — inflamação normal; não confundir com infecção.",
    "vo":"Nas primeiras semanas, as bordas da ferida da criança ficam levemente avermelhadas e um pouco endurecidas. Isso é inflamação normal de cicatrização — não confundir com infecção."},
   {"k":"Fique de olho","sc":["Vermelho,","calor ou pus?"],"e":None,
    "sub":"Vermelhidão crescente · calor · secreção · bordas abertas · febre.",
    "vo":"Olhe a ferida todo dia: vermelhidão que vai além das bordas e aumenta, calor, secreção amarela ou com cheiro, bordas que se abriram, ou febre. Qualquer um desses merece atenção."},
   {"k":"Sinal de alarme","sc":["Mais agitação","e febre?"],"e":None,"motif":"no",
    "sub":"3 As + febre + ferida aberta ou pus → pronto-socorro.",
    "vo":"Na criança, fique atento: agitação que piora, choro sem motivo, febre, ferida que abriu ou pus são sinais de que algo não vai bem. Pronto-socorro na hora e avise a equipe."},
   {"k":"Resumo","sc":["Curativo seco,","olho na ferida."],"e":"seco",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: curativo seco e limpo, sem deixar a criança mexer, e olho nos sinais todos os dias. Dúvida do dia a dia, fale com a gente; sinal de alarme, pronto-socorro."},
  ],
  "caption":"Seu filho operou e está em casa com a ferida? Curativo seco, sem deixar mexer, sem molhar antes da liberação — e atenção a vermelhidão crescente, pus, ferida aberta, agitação e febre: pronto-socorro.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 # ── ⑦ Dor pós-operatória: normal × alarme ────────────────────────────────────────────
 # Arquétipo gancho: micro_caso (adulto) · pergunta (kids). Palette: noturno_azul / verde_clinico.
 # Fontes: AAOS; UpToDate Acute postoperative pain; SBOT guidelines.
 {"id":"dor_posop","ep":13,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"noturno_azul",
  "scenes":[
   {"k":"CHEGOU EM CASA","sc":["A dor é","normal ou alarme?"],"e":None,
    "sub":"Saber a diferença é o que protege a recuperação.",
    "vo":"Você chegou em casa após a cirurgia — e tem dor. Mas como saber se é a dor esperada ou um sinal de que algo não vai bem? É o que vou te mostrar agora."},
   {"k":"Dor normal","sc":["Diminui a","cada dia."],"e":"Diminui",
    "sub":"Responde ao remédio prescrito e vai cedendo progressivamente.",
    "vo":"A dor normal do pós-operatório vai diminuindo a cada dia. Ela responde ao analgésico prescrito e, mesmo que incomode, você consegue descansar e se mover com cautela."},
   {"k":"Use o remédio","sc":["No horário,","não espere a dor."],"e":"horário",
    "sub":"Analgésico preventivo funciona melhor do que esperar a dor aparecer.",
    "vo":"O analgésico prescrito funciona melhor quando tomado no horário, antes de a dor se instalar. Não espere chegar no limite — analgesia preventiva é mais eficiente."},
   {"k":"Sinal de alerta","sc":["Dor que","vai aumentando."],"e":"aumentando",
    "sub":"Se cresce no lugar de diminuir — mesmo com o remédio — atenção.",
    "vo":"O sinal de alerta é a dor que aumenta em vez de diminuir — especialmente se não passa nem com o remédio, ou se mudou de caráter: ficou constante, pulsante, em pressão. Isso não é normal."},
   {"k":"Sinal grave","sc":["Dor ao mexer","os dedos?"],"e":None,"motif":"no",
    "sub":"Dor ao movimentar passivamente dedos/artelhos pode indicar compressão da circulação.",
    "vo":"Um sinal mais grave: dor intensa ao mover os dedos ou artelhos passivamente, mesmo que a cirurgia não tenha sido neles. Pode ser sinal precoce de compressão da circulação — não espere."},
   {"k":"Sinal de alarme","sc":["Pronto-socorro","se tiver:"],"e":None,"motif":"no",
    "sub":"Dor crescente que não cede ao remédio · nova/diferente · com dedos roxos ou frios.",
    "vo":"Diante de dor que não passa nem com o remédio, que vai aumentando, ou que veio acompanhada de dedos roxos ou frios, vá ao pronto-socorro e avise a equipe. Compressão tratada cedo não deixa sequela."},
   {"k":"Resumo","sc":["Dor diminui?","Ótimo. Aumenta?"],"e":None,
    "sub":"Dor normal diminui. Dor que cresce com remédio insuficiente → pronto-socorro.",
    "vo":"Resumindo: dor que diminui a cada dia e responde ao analgésico é normal. Dor que cresce, não cede ou mudou de caráter — pronto-socorro e avise a equipe. Dúvida do dia a dia, fale com a gente no WhatsApp."},
  ],
  "caption":"Chegou em casa com dor depois da cirurgia? Dor normal diminui a cada dia e responde ao remédio. Dor crescente que não cede, nova/diferente, ou com dedos roxos/frios: pronto-socorro imediato — pode ser compressão da circulação.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"dor_posop_kids","ep":14,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"verde_clinico",
  "scenes":[
   {"k":"VOCÊ SABIA?","sc":["Dor crescente","não é normal?"],"e":"crescente",
    "sub":"Saber essa diferença é o que protege o seu filho.",
    "vo":"Sabia que a dor que vai aumentando depois da cirurgia não é o esperado? A dor normal do pós-op diminui a cada dia. Quando cresce, é sinal de que algo precisa de atenção."},
   {"k":"Dor normal","sc":["Diminui a","cada dia."],"e":"Diminui",
    "sub":"Responde ao analgésico prescrito e vai cedendo progressivamente.",
    "vo":"A dor normal do pós-operatório da criança diminui a cada dia. Ela responde ao analgésico prescrito e a criança consegue dormir, comer e se distrair."},
   {"k":"Use o remédio","sc":["No horário,","não espere."],"e":"horário",
    "sub":"Analgésico preventivo é mais eficiente — não espere a criança chorar muito.",
    "vo":"Dê o analgésico no horário prescrito — não espere a criança chegar no limite da dor para dar. Analgesia preventiva é mais eficaz e poupa a criança do sofrimento desnecessário."},
   {"k":"Sinal de alerta","sc":["Mais remédio","do que antes?"],"e":"antes",
    "sub":"Precisar de mais analgésico para o mesmo resultado — atenção.",
    "vo":"Se a criança começar a pedir mais remédio do que nas primeiras horas ou dias, ou se mesmo com o remédio ela continua chorando e agitada — é sinal de que a dor está aumentando, não diminuindo."},
   {"k":"Sinal grave","sc":["Não mexe o","braço ou a perna?"],"e":None,"motif":"no",
    "sub":"Criança que para de mover o membro espontaneamente pode ter compressão.",
    "vo":"Um sinal mais grave: a criança que espontaneamente para de mover o braço ou a perna, ou que chora muito quando você tenta dobrar os dedos suavemente. Pode ser sinal precoce de compressão — não espere."},
   {"k":"Sinal de alarme","sc":["Pronto-socorro","se tiver:"],"e":None,"motif":"no",
    "sub":"3 As + dor crescente com remédio insuficiente · dedos roxos ou frios.",
    "vo":"Diante dos 3 As — mais analgésico, mais ansiedade, mais agitação — some a dedos roxos, pálidos ou frios, ou criança que parou de mover o membro. Pronto-socorro na hora e avise a equipe."},
   {"k":"Resumo","sc":["Dor diminui?","Ótimo. Aumenta?"],"e":None,
    "sub":"Dor normal diminui. Dor que cresce → pronto-socorro.",
    "vo":"Resumindo: dor que diminui e responde ao analgésico é normal. Dor que cresce ou não cede — pronto-socorro e avise a equipe. Dúvida do dia a dia, fale com a gente no WhatsApp."},
  ],
  "caption":"Seu filho voltou da cirurgia com dor? Dor normal diminui a cada dia e responde ao remédio. Dor crescente com mais analgésico que antes, agitação e dedos roxos/frios: pronto-socorro imediato.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 # ── ⑧ Inchaço / edema ────────────────────────────────────────────────────────────────
 # Arquétipo gancho: alerta (adulto) · mito_vs_verdade (kids). Palette: carvao_quente / noturno_azul.
 # Fontes: SBOT; UpToDate Post-op edema; orthopaedics literature on DVT vs surgical edema.
 {"id":"edema","ep":15,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"carvao_quente",
  "scenes":[
   {"k":"ATENÇÃO","sc":["Inchaço depois","da cirurgia."],"e":"Inchaço",
    "sub":"Normal nos primeiros dias — mas há sinais que pedem atenção imediata.",
    "vo":"Inchaço depois de uma cirurgia é esperado — e pode assustar. Mas ele tem um padrão normal, e há sinais que fogem desse padrão e pedem atenção imediata."},
   {"k":"Por que incha","sc":["Inflamação da","cicatrização."],"e":"Inflamação",
    "sub":"O corpo envia mais sangue e fluido para a área — é parte da cicatrização.",
    "vo":"O corpo envia sangue e fluido extra para a área operada para cicatrizar o tecido. O resultado é o inchaço — especialmente nos primeiros dois ou três dias, quando costuma estar no pico."},
   {"k":"Elevação","sc":["Elevação","controla o edema."],"e":"Elevação",
    "sub":"Membro acima do coração, sempre que em repouso — em toda a recuperação.",
    "vo":"A principal forma de controlar o inchaço é elevar o membro acima do coração sempre que estiver parado. Isso drena o fluido por gravidade e é o remédio mais eficiente para o edema do pós-op."},
   {"k":"Quanto tempo?","sc":["Semanas a","meses."],"e":None,
    "sub":"Reduz com o tempo, mas pode levar semanas; movimento ajuda.",
    "vo":"O inchaço vai diminuindo com o tempo — mas pode levar semanas ou até meses para sumir completamente. Mover o membro dentro do permitido ajuda a bombear o fluido de volta."},
   {"k":"Fique de olho","sc":["Inchaço que","aumenta rápido?"],"e":None,
    "sub":"Aumento súbito, vermelhidão, calor e dor na panturrilha podem ser TVP.",
    "vo":"Fique atento: inchaço que aumenta de forma súbita, especialmente numa perna muito mais que na outra, com vermelhidão, calor e dor na panturrilha, pode ser sinal de trombose — uma complicação que precisa de avaliação urgente."},
   {"k":"Sinal de alarme","sc":["Pronto-socorro","se tiver:"],"e":None,"motif":"no",
    "sub":"Inchaço súbito · panturrilha dolorosa · vermelho/quente · falta de ar.",
    "vo":"Diante de inchaço que aumenta abruptamente, panturrilha dolorosa e inchada especialmente em repouso, vermelhidão, calor, ou falta de ar, vá ao pronto-socorro e avise a equipe. Não espere."},
   {"k":"Resumo","sc":["Elevação,","olho no padrão."],"e":"Elevação",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: inchaço gradual que vai diminuindo é normal — elevação é o tratamento. Inchaço súbito, assimétrico ou com outros sinais: pronto-socorro. Dúvida do dia a dia, fale com a gente."},
  ],
  "caption":"Operou e está inchado? Inchaço gradual nos primeiros dias é normal — elevação acima do coração é o tratamento. Inchaço súbito, panturrilha dolorosa, vermelhidão ou falta de ar: pronto-socorro imediato (pode ser trombose).\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},

 {"id":"edema_kids","ep":16,"temporada":"pos_operatorio","serie":"Recuperação","motif_family":"bone",
  "palette":"noturno_azul",
  "scenes":[
   {"k":"MITO OU VERDADE?","sc":["Inchaço pós-op","sempre é perigoso?"],"e":"sempre",
    "sub":"Mito — inchaço gradual é normal. Mas o padrão importa.",
    "vo":"Muitas famílias ficam apavoradas com o inchaço depois da cirurgia da criança. Mas inchaço gradual nos primeiros dias é esperado — parte normal da cicatrização. O que importa é o padrão."},
   {"k":"Por que incha","sc":["O corpo está","cicatrizando."],"e":"cicatrizando",
    "sub":"Fluido extra vai para a área operada — reduz progressivamente.",
    "vo":"O corpo da criança envia fluido extra para a área operada para cicatrizar. O resultado é o inchaço — especialmente nos primeiros dois ou três dias. Depois, diminui progressivamente."},
   {"k":"Elevação","sc":["Elevação","desincha."],"e":"Elevação",
    "sub":"Membro acima do coração, sempre que em repouso — em toda a recuperação.",
    "vo":"Elevar o membro operado acima do coração sempre que a criança estiver parada é o que drena o fluido e controla o inchaço. Faz isso durante toda a recuperação."},
   {"k":"Quanto tempo?","sc":["Semanas,","gradual."],"e":None,
    "sub":"Mover dentro do permitido ajuda — mas o inchaço pode demorar a sumir.",
    "vo":"O inchaço pode levar semanas para sumir completamente. Movimento dentro do permitido ajuda. Não se assuste se ainda estiver inchado depois de alguns dias — o que importa é a tendência de melhora."},
   {"k":"Fique de olho","sc":["Perna muito mais","inchada que a outra?"],"e":None,
    "sub":"Inchaço assimétrico súbito com dor e calor merece atenção urgente.",
    "vo":"Fique atento: se uma perna ficar muito mais inchada de forma súbita que a outra, especialmente com vermelhidão, calor e dor na panturrilha, pode ser sinal de trombose."},
   {"k":"Sinal de alarme","sc":["Mais agitação","e membro muito inchado?"],"e":None,"motif":"no",
    "sub":"3 As + inchaço súbito · calor · vermelhidão · falta de ar.",
    "vo":"Na criança, agitação que piora com inchaço súbito, calor e vermelhidão, ou se ela ficar com falta de ar — pronto-socorro na hora e avise a equipe."},
   {"k":"Resumo","sc":["Elevação,","olho no padrão."],"e":"Elevação",
    "sub":"Dúvida de rotina: WhatsApp (11) 3280-1413.",
    "vo":"Resumindo: inchaço gradual é normal, elevação é o tratamento. Inchaço súbito e assimétrico com outros sinais — pronto-socorro. Dúvida do dia a dia, fale com a gente."},
  ],
  "caption":"Seu filho está inchado após a cirurgia? Inchaço gradual nos primeiros dias é normal — elevação acima do coração ajuda. Inchaço súbito, assimétrico, com calor e agitação ou falta de ar: pronto-socorro imediato.\n\nDr. Rafael Vargas · CRM-SP 226103 · RQE 137901 — Reconstrução e Alongamento Ósseo · Ortopedia Pediátrica.\nConteúdo educativo, não substitui a avaliação do seu médico."},
]
