# -*- coding: utf-8 -*-
"""Dados das temporadas serializadas. Cada dia = 5 frames (segmento, titulo, sub, cue).
Ordem dos dias: seg, ter, qua, qui, sex, sab, dom."""
SEASONS = []

# ===================== SEMANA 1 — JOELHO =====================
SEASONS.append({"slug":"joelho","theme":"Semana do Joelho","days":[
 # SEG · O que observar
 [("SEG · O que observar","Joelho da criança: 4 sinais que pedem avaliação","E um que assusta os pais, mas sozinho costuma ser normal. Vem comigo nos próximos cards.","deslize →"),
  ("Sinais 1 e 2","Incha ou trava","Joelho que incha depois do esforço, ou que “trava” e não estende direito, merece avaliação — não é só pancada boba.","continua →"),
  ("Sinais 3 e 4","Dói à noite ou faz mancar","Dor que acorda a criança, sempre no mesmo ponto, ou que faz mancar por mais de um ou dois dias: vale avaliar.","continua →"),
  ("O que costuma ser normal","O estalo sem dor","Joelho que estala ao agachar, sem dor, inchaço ou falseio, quase sempre não preocupa. O que muda tudo é vir com dor.","quase lá →"),
  ("Guarde isso","Na dúvida, observe e avalie","Salve para lembrar dos sinais e mande para um pai ou mãe. Avaliar cedo costuma simplificar tudo.","Amanhã: perna em X ou arqueada — é só fase do crescimento? →")],
 # TER · Na criança (deformidade / reconstrução)
 [("TER · Na criança","Perna em X ou arqueada: é só fase?","Ontem vimos os sinais. Hoje, o alinhamento das perninhas — quando é do crescimento e quando o osso pede atenção.","deslize →"),
  ("O que é comum","Muda com a idade","O bebê costuma ter as pernas arqueadas; por volta dos 3 anos vira um leve X; depois alinha. Faz parte do desenvolvimento.","continua →"),
  ("Quando observar","Os sinais de atenção","Muito acentuado, só de um lado, que piora, ou junto com baixa estatura: vale avaliar a causa.","continua →"),
  ("A virada","Nem toda perna torta é igual","A maioria alinha sozinha. Algumas precisam de acompanhamento e, em parte dos casos, de correção guiada do crescimento.","quase lá →"),
  ("Guarde isso","Compare os dois lados","Assimetria que aumenta merece avaliação. Salve e mande para outra mãe ou pai.","Amanhã: “estalo no joelho é desgaste”? O mito que mais ouço. →")],
 # QUA · Mito x Verdade
 [("QUA · Mito x Verdade","“Estalo no joelho é desgaste”","Ontem, o alinhamento. Hoje, o mito que mais escuto no consultório sobre o joelho do adolescente.","deslize →"),
  ("O mito","O que dizem por aí","Que todo estalo (a tal crepitação) é sinal de desgaste e que o jovem precisa parar de se mexer.","continua →"),
  ("A verdade","O que costuma ser","Estalo sem dor, inchaço ou falseio quase sempre é benigno — tendões e cartilagem deslizando. Movimento é aliado.","continua →"),
  ("Quando muda","O que liga o alerta","Estalo COM dor, inchaço, travamento ou sensação de falsear é diferente: aí sim, avalie.","quase lá →"),
  ("Guarde isso","Sem dor, fique tranquilo","Salve para mostrar a quem vive preocupado com o estalo do filho.","Amanhã: a dor abaixo do joelho de quem treina. →")],
 # QUI · No esporte (Osgood-Schlatter)
 [("QUI · No esporte","Dor abaixo do joelho em quem treina","Ontem, o mito do estalo. Hoje, a queixa nº 1 do adolescente atleta: a Osgood-Schlatter.","deslize →"),
  ("O que é","Onde e por quê","Dor (às vezes um caroço) logo abaixo da patela, na fase de estirão, por tração repetida do tendão no osso que cresce.","continua →"),
  ("O que ajuda","O manejo","Ajustar a carga de treino, gelo após a atividade e alongar costumam aliviar. Raramente é preciso parar tudo.","continua →"),
  ("A virada","Costuma passar","Tende a melhorar quando o crescimento se completa. O acompanhamento evita que a dor limite o esporte.","quase lá →"),
  ("Guarde isso","Dor que limita, avalie","Salve e mande para um pai ou mãe de jovem atleta.","Amanhã: e se ele TORCER o joelho no jogo? Os primeiros minutos. →")],
 # SEX · Primeiros socorros
 [("SEX · Primeiros socorros","Torceu o joelho no jogo: e agora?","Sexta é dia de guardar para a emergência. Os primeiros minutos de uma torção de joelho.","deslize →"),
  ("Passo 1","Pare e proteja","Tire do jogo e não force o apoio. “Continuar pra ver se passa” é o erro mais comum.","continua →"),
  ("Passo 2","Gelo e eleve","Gelo com um pano por 15 minutos, perna elevada, repouso. Nada de água quente ou massagem forte agora.","continua →"),
  ("Sinal de alerta","O que muda tudo","Não conseguir apoiar, joelho que incha rápido ou que “sai do lugar”: procure avaliação.","quase lá →"),
  ("Guarde isso","Salve para a emergência","Mande para o grupo do time ou da escola. Pode ajudar na hora certa.","Amanhã: quando o joelho inchado vira caso de avaliar sem demora. →")],
 # SAB · Quando procurar
 [("SAB · Quando procurar","Joelho que incha, trava ou falseia","Fim de semana com a família. Os sinais do joelho que pedem avaliação sem demora.","deslize →"),
  ("Sinal 1","Incha sempre que joga","Inchaço que volta a cada esforço, mesmo sem trauma claro, merece um olhar.","continua →"),
  ("Sinal 2","Trava ou falseia","Joelho que “tranca” e não estende, ou que dá a sensação de sair do lugar, não é o esperado.","continua →"),
  ("Sinal 3","Dói à noite ou faz mancar","Dor que acorda, ou que faz mancar por dias, sempre vale avaliar.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Avaliar cedo costuma simplificar. Salve e compartilhe.","Amanhã, o fecho: o joelho torto que NÃO corrige sozinho — como eu trato. →")],
 # DOM · Como eu penso (reconstrução)
 [("DOM · Como eu penso","O joelho torto que não corrige sozinho","Fechando a Semana do Joelho: quando o desalinhamento persiste e como penso o tratamento.","deslize →"),
  ("O contexto","Quando não é só fase","Desalinhamento que aumenta, é assimétrico ou tem uma causa (sequela, doença óssea) pode sobrecarregar o joelho ao longo do tempo.","continua →"),
  ("O caminho","Correção guiada e por etapas","Dá para medir o eixo, planejar e, muitas vezes, guiar o crescimento ou corrigir de forma gradual e acompanhada.","continua →"),
  ("O princípio","Função em primeiro lugar","O foco nunca é estético — é alinhar para proteger a articulação e melhorar como a criança anda e vive.","quase lá →"),
  ("Converse comigo","Todo joelho torto tem um caminho","Casos complexos têm avaliação cuidadosa e plano realista. Fale comigo no WhatsApp da bio.","Semana que vem: Tornozelo e Pé. Até lá! →")],
]})

# ===================== SEMANA 2 — TORNOZELO E PÉ =====================
SEASONS.append({"slug":"tornozelo","theme":"Semana do Tornozelo e Pé","days":[
 [("SEG · O que observar","Torceu o tornozelo: 4 coisas para observar","Esta semana é sobre tornozelo e pé. Hoje, o que olhar nas primeiras horas de uma torção.","deslize →"),
  ("Sinais 1 e 2","Incha e muda de cor","Inchaço que aumenta rápido e mancha roxa grande pedem mais atenção que uma torção leve.","continua →"),
  ("Sinais 3 e 4","Não apoia o pé","Se a criança não consegue pisar, ou dói muito num ponto do osso, vale avaliar.","continua →"),
  ("O que costuma ser leve","A torção comum","Inchaço pequeno, consegue apoiar, melhora em dias: costuma ser entorse leve. Proteger e gelar ajuda.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve para a próxima torção e mande para outro pai ou mãe.","Amanhã: pé chato na criança preocupa? →")],
 [("TER · Na criança","Pé chato na criança preocupa?","Ontem, a torção. Hoje, a dúvida clássica dos pais: o pezinho sem arco.","deslize →"),
  ("O que é comum","O arco se forma com o tempo","Quase todo bebê tem pé “chato”; o arco costuma aparecer ao longo da infância. Na maioria, é só desenvolvimento.","continua →"),
  ("Quando observar","Os sinais de atenção","Dor, rigidez, pé que não se mexe direito, ou que é chato só de um lado: vale avaliar.","continua →"),
  ("A virada","Palmilha resolve tudo? Nem sempre","A maioria não precisa de nada. A indicação depende do exame, não só da aparência do pé.","quase lá →"),
  ("Guarde isso","Descalço em casa fortalece","Salve e mande para quem vive preocupado com o pé do filho.","Amanhã: “criança não torce sério”? Mito. →")],
 [("QUA · Mito x Verdade","“Criança não torce sério, é só dengo”","Ontem, o pé chato. Hoje, um mito que pode atrasar um diagnóstico.","deslize →"),
  ("O mito","O que dizem","Que dor de criança depois de torcer é sempre manha e passa sozinha.","continua →"),
  ("A verdade","O osso que cresce é diferente","Na criança, a placa de crescimento é frágil: o que parece “só torção” às vezes é uma fratura que não aparece fácil.","continua →"),
  ("Quando muda","O sinal que pede raio-X","Dor exatamente sobre o osso, não apoiar o pé ou inchaço importante: avalie, pode precisar de imagem.","quase lá →"),
  ("Guarde isso","Na dúvida, não force","Salve para lembrar e mande para outra família.","Amanhã: torceu jogando — quando voltar? →")],
 [("QUI · No esporte","Torceu jogando: quando voltar?","Ontem, o mito. Hoje, a pergunta do atleta: quando é seguro voltar ao esporte.","deslize →"),
  ("Não é só “sumiu a dor”","Os critérios","Voltar cedo demais é a maior causa de torcer de novo. Não basta a dor passar.","continua →"),
  ("O que conta","Força, equilíbrio e confiança","Apoiar firme, equilibrar num pé só, correr e mudar de direção sem medo — aí o tornozelo está pronto.","continua →"),
  ("A virada","Fortalecer protege","Exercícios de equilíbrio reduzem muito o risco de uma nova torção. Vale a pena.","quase lá →"),
  ("Guarde isso","Pressa hoje, lesão amanhã","Salve e mande para um pai ou mãe de jovem atleta.","Amanhã: primeiros minutos de uma torção feia. →")],
 [("SEX · Primeiros socorros","Torceu o pé: os primeiros minutos","Sexta de guardar para a emergência. O passo a passo da torção de tornozelo.","deslize →"),
  ("Passo 1","Proteja e eleve","Pare a atividade, tire o tênis com cuidado e eleve o pé. Não force o apoio para “testar”.","continua →"),
  ("Passo 2","Gelo, sim; calor, não","Gelo com pano por 15 minutos. Nas primeiras horas, nada de água quente, pomada de calor ou massagem forte.","continua →"),
  ("Sinal de alerta","Quando ir logo","Não apoiar de jeito nenhum, deformidade visível ou dor muito forte sobre o osso: procure atendimento.","quase lá →"),
  ("Guarde isso","Salve para a emergência","Mande para o grupo da escola ou do time.","Amanhã: a torção que não melhora — quando avaliar. →")],
 [("SAB · Quando procurar","Torção que não melhora: quando avaliar","Fim de semana em família. Os sinais de que aquela torção precisa de um olhar.","deslize →"),
  ("Sinal 1","Dor que não cede em dias","Entorse leve melhora aos poucos. Dor que persiste ou piora merece avaliação.","continua →"),
  ("Sinal 2","Tornozelo que “sai do lugar”","Sensação de instabilidade ou de falsear ao pisar não é o esperado.","continua →"),
  ("Sinal 3","Incha sempre que anda","Inchaço que volta a cada caminhada, mesmo semanas depois, vale investigar.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve e compartilhe com quem precisa.","Amanhã, o fecho: pé torto e deformidades do pé — como eu trato. →")],
 [("DOM · Como eu penso","Pé torto e deformidades do pé","Fechando a semana: quando o pé nasce ou fica com uma forma que atrapalha — e como penso o tratamento.","deslize →"),
  ("O contexto","Há vários tipos","Do pé torto congênito (já no nascimento) a deformidades por sequelas ou doenças — cada um tem o seu caminho.","continua →"),
  ("O caminho","Começar cedo, corrigir por etapas","No pé torto, gessos que corrigem aos poucos (método de Ponseti) costumam evitar cirurgias maiores. Em outros casos, correção guiada e acompanhada.","continua →"),
  ("O princípio","Um pé que funcione","O objetivo é um pé que apoie, calce sapato e ande bem — função e conforto, não aparência.","quase lá →"),
  ("Converse comigo","Todo pé tem um caminho","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: o Quadril do bebê e da criança. →")],
]})

# ===================== SEMANA 3 — QUADRIL =====================
SEASONS.append({"slug":"quadril","theme":"Semana do Quadril","days":[
 [("SEG · O que observar","Criança mancando: o que observar","Esta semana é sobre o quadril. Hoje, o que olhar quando a criança começa a mancar.","deslize →"),
  ("Sinais 1 e 2","Mancar sem ter batido","Mancar que aparece sem queda nem pancada, ou que dura mais de um dia, merece atenção.","continua →"),
  ("Sinal 3","Dor no quadril… ou no joelho","O quadril às vezes “avisa” doendo no joelho ou na coxa. Dor no joelho sem motivo também olha o quadril.","continua →"),
  ("Atenção","Com febre, é diferente","Mancar com febre, dor forte e recusa a mexer a perna pede avaliação sem demora.","quase lá →"),
  ("Guarde isso","Mancar não é frescura","Salve e mande para outra família.","Amanhã: os sinais de displasia no bebê. →")],
 [("TER · Na criança","Displasia do quadril: sinais no bebê","Ontem, a criança que manca. Hoje, o quadril do bebê — quanto antes, mais simples.","deslize →"),
  ("O que é","O quadril que não encaixa","Na displasia, a cabeça do fêmur não se encaixa bem desde cedo. Identificar nos primeiros meses costuma facilitar tudo.","continua →"),
  ("Sinais","O que observar na troca de fralda","Pregas das coxas assimétricas, uma perna que parece mais curta ou dificuldade de abrir uma das pernas.","continua →"),
  ("Importante","O teste do pezinho não detecta","A avaliação é clínica e, às vezes, com ultrassom. Por isso o exame do bebê pelo ortopedista faz diferença.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie cedo","Salve e mande para quem tem bebê em casa.","Amanhã: “andador ajuda a andar”? Mito. →")],
 [("QUA · Mito x Verdade","“Andador ajuda o bebê a andar”","Ontem, a displasia. Hoje, um mito comum sobre o desenvolvimento das perninhas.","deslize →"),
  ("O mito","O que se diz","Que andador e pôr de pé cedo aceleram o andar e fortalecem as pernas.","continua →"),
  ("A verdade","Não acelera — e tem risco","O andador não antecipa o andar e é causa frequente de quedas e acidentes. Sociedades de pediatria desaconselham.","continua →"),
  ("O que ajuda","Chão livre e tempo","O que fortalece de verdade é engatinhar e explorar o chão com segurança, no tempo da criança.","quase lá →"),
  ("Guarde isso","Cada bebê tem seu tempo","Salve e mande para os avós também.","Amanhã: a dor no quadril do adolescente. →")],
 [("QUI · No esporte","Dor no quadril do adolescente","Ontem, o mito do andador. Hoje, a dor no quadril de quem treina — e um alerta importante.","deslize →"),
  ("O comum","Sobrecarga e estirão","No estirão, tendões e áreas de crescimento do quadril sofrem com treino intenso. Ajustar a carga costuma ajudar.","continua →"),
  ("O alerta","Mancar + dor na virilha","No pré-adolescente, dor na virilha ou coxa com mancar, sem trauma claro, merece avaliação sem demora.","continua →"),
  ("Por quê","Algumas coisas têm hora","Certas condições do quadril nessa idade respondem muito melhor quando avaliadas cedo.","quase lá →"),
  ("Guarde isso","Dor que faz mancar, avalie","Salve e mande para um pai de jovem atleta.","Amanhã: a criança que de repente não quer andar. →")],
 [("SEX · Primeiros socorros","A criança que de repente não anda","Sexta de guardar para a emergência. O que fazer quando a criança para de apoiar a perna.","deslize →"),
  ("Passo 1","Observe e não force","Não obrigue a andar nem “estale” a perna. Veja se há inchaço, calor ou um ponto de dor.","continua →"),
  ("Passo 2","Meça a temperatura","Febre junto com recusa a andar e dor muda a urgência: pode precisar de avaliação no mesmo dia.","continua →"),
  ("Sinal de alerta","Quando ir logo","Dor forte, febre, perna “parada” numa posição ou muito inchaço: procure atendimento.","quase lá →"),
  ("Guarde isso","Recusar andar é um sinal","Salve para a emergência e compartilhe.","Amanhã: o mancar que volta — quando avaliar. →")],
 [("SAB · Quando procurar","Mancar que vai e volta: quando avaliar","Fim de semana em família. Os sinais de que o mancar precisa de um olhar.","deslize →"),
  ("Sinal 1","Volta sempre no mesmo lado","Mancar que reaparece, sempre na mesma perna, merece investigação.","continua →"),
  ("Sinal 2","Vem com cansaço ou dor noturna","Mancar com dor que acorda, ou cansaço fora do normal, vale avaliar.","continua →"),
  ("Sinal 3","Perna que parece mais curta","Diferença no comprimento ou no jeito de andar que aumenta com o tempo: avalie.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve e mande para quem precisa.","Amanhã, o fecho: o quadril que precisa de reconstrução. →")],
 [("DOM · Como eu penso","O quadril que precisa de mais","Fechando a semana: quando o quadril da criança precisa de tratamento por etapas.","deslize →"),
  ("O contexto","Displasia, Perthes e sequelas","Algumas condições mudam a forma ou o encaixe do quadril ao longo do crescimento e pedem acompanhamento de perto.","continua →"),
  ("O caminho","Acompanhar, preservar, corrigir","O plano vai de observar e proteger a articulação a corrigir de forma guiada quando necessário — sempre por etapas.","continua →"),
  ("O princípio","Pensar no quadril adulto","Cuidar bem na infância protege a articulação para a vida toda. Função e durabilidade vêm primeiro.","quase lá →"),
  ("Converse comigo","Cada quadril tem um plano","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: a Coluna na infância e adolescência. →")],
]})

# ===================== SEMANA 4 — COLUNA =====================
SEASONS.append({"slug":"coluna","theme":"Semana da Coluna","days":[
 [("SEG · O que observar","Escoliose: 3 sinais para observar em casa","Esta semana é sobre a coluna. Hoje, um teste simples que dá para fazer em casa.","deslize →"),
  ("Sinal 1","Ombros ou cintura tortos","Um ombro mais alto, uma cintura assimétrica ou a roupa que “cai torto” podem ser sinais.","continua →"),
  ("O teste","Inclinar o tronco à frente","Peça para inclinar o tronco à frente, braços soltos. Olhe as costas por trás: um lado mais alto chama atenção.","continua →"),
  ("Importante","Costuma ser indolor no início","A escoliose muitas vezes não dói no começo — por isso observar a postura ajuda a perceber cedo.","quase lá →"),
  ("Guarde isso","Quanto antes, mais simples","Salve o teste e mande para outra mãe ou pai.","Amanhã: escoliose na adolescência, explicada. →")],
 [("TER · Na criança","Escoliose na adolescência","Ontem, o teste em casa. Hoje, o que é a escoliose e por que o acompanhamento importa.","deslize →"),
  ("O que é","Uma curva na coluna","A coluna, que de costas deveria ser reta, ganha uma curva. Na maioria, a causa não é “má postura” nem peso de mochila.","continua →"),
  ("Quando aparece","O estirão é o momento-chave","Costuma surgir ou piorar no estirão. Por isso acompanhar de perto nessa fase faz diferença.","continua →"),
  ("A virada","Nem toda curva é igual","Curvas pequenas muitas vezes só são acompanhadas; outras precisam de colete ou tratamento. O exame é que diz.","quase lá →"),
  ("Guarde isso","Acompanhar muda o desfecho","Salve e mande para quem tem adolescente em casa.","Amanhã: “foi a mochila que entortou”? Mito. →")],
 [("QUA · Mito x Verdade","“A mochila entortou a coluna dele”","Ontem, a escoliose. Hoje, o mito que confunde mochila com a causa.","deslize →"),
  ("O mito","O que se diz","Que mochila pesada e má postura são a causa da escoliose.","continua →"),
  ("A verdade","São coisas diferentes","A escoliose, na maioria, não vem da mochila. Mochila pesada causa dor e sobrecarga — só não “entorta” a coluna.","continua →"),
  ("O que fazer","Cuidar das duas coisas","Aliviar a mochila ajuda nas dores; observar a postura ajuda a perceber a escoliose cedo. Cada uma no seu lugar.","quase lá →"),
  ("Guarde isso","Mito esclarecido","Salve e mande para a escola e outros pais.","Amanhã: dor nas costas no jovem que treina. →")],
 [("QUI · No esporte","Dor nas costas no jovem atleta","Ontem, o mito da mochila. Hoje, a dor nas costas de quem treina — e quando preocupa.","deslize →"),
  ("O comum","Sobrecarga muscular","Treino intenso e core fraco causam dor muscular, que costuma melhorar com ajuste e fortalecimento.","continua →"),
  ("O alerta","A dor que pede atenção","Dor que acorda à noite, que piora ao estender as costas ou que limita o treino merece avaliação.","continua →"),
  ("A virada","Fortalecer o core protege","Boa preparação física e técnica reduzem muito as dores nas costas no esporte.","quase lá →"),
  ("Guarde isso","Dor que limita, avalie","Salve e mande para um pai de jovem atleta.","Amanhã: a mochila certa para a volta às aulas. →")],
 [("SEX · Primeiros socorros","A mochila certa (poupe as costas)","Sexta de guardar e usar. Como ajustar a mochila para não pesar nas costas.","deslize →"),
  ("Regra do peso","No máximo 10–15% do peso","A mochila cheia não deveria passar de 10 a 15% do peso da criança. Pese de vez em quando.","continua →"),
  ("Como usar","Dois ombros e perto do corpo","Use sempre nos dois ombros, com alças largas e ajustada perto das costas. Mochila de rodinha é alternativa.","continua →"),
  ("O que evitar","Pendurar num ombro só","Carregar de lado, frouxa ou cheia do que não usa é o que mais sobrecarrega.","quase lá →"),
  ("Guarde isso","Salve para a volta às aulas","Mande para a escola e o grupo de pais.","Amanhã: dor nas costas que precisa de avaliação. →")],
 [("SAB · Quando procurar","Dor nas costas na criança: quando avaliar","Fim de semana em família. Os sinais de que a dor nas costas pede um olhar.","deslize →"),
  ("Sinal 1","Dor que acorda à noite","Dor que tira do sono, que não passa com repouso, vale avaliar.","continua →"),
  ("Sinal 2","Com febre ou perda de peso","Dor acompanhada de febre, emagrecimento ou cansaço merece avaliação sem demora.","continua →"),
  ("Sinal 3","Que limita o dia a dia","Dor que atrapalha brincar, andar ou faz a criança parar de fazer o que gosta: avalie.","quase lá →"),
  ("Guarde isso","Quase sempre é simples, mas investigue","Salve e compartilhe.","Amanhã, o fecho: a escoliose que progride — como trato. →")],
 [("DOM · Como eu penso","A escoliose que progride","Fechando a semana: quando a curva aumenta e como penso o acompanhamento e o tratamento.","deslize →"),
  ("O contexto","O tamanho e o crescimento contam","Curvas maiores ou que crescem rápido no estirão precisam de mais que observação.","continua →"),
  ("O caminho","De observar a colete e cirurgia","Conforme o caso: acompanhamento próximo, colete para frear a progressão ou, em curvas grandes, correção cirúrgica planejada.","continua →"),
  ("O princípio","Decidir com transparência","Cada etapa é decidida junto com a família, pesando risco, benefício e o momento do crescimento.","quase lá →"),
  ("Converse comigo","Cada coluna tem um plano","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: Pernas tortas e desalinhamento. →")],
]})

# ===================== SEMANA 5 — PERNAS TORTAS (alinhamento) =====================
SEASONS.append({"slug":"pernas","theme":"Semana das Pernas Tortas","days":[
 [("SEG · O que observar","Perna torta: o que observar no crescimento","Esta semana é sobre o alinhamento das pernas. Hoje, o que olhar e quando é só fase.","deslize →"),
  ("Sinal 1","Compare os dois lados","Pernas que mudam juntas costumam ser desenvolvimento. Torto só de um lado chama atenção.","continua →"),
  ("Sinal 2","Piora em vez de melhorar","O esperado é alinhar com a idade. Desalinhamento que aumenta merece avaliação.","continua →"),
  ("O que costuma ser normal","Varo e valgo têm idade","Perna arqueada no bebê e leve X na pré-escola são comuns e costumam se resolver sozinhos.","quase lá →"),
  ("Guarde isso","Foto a cada poucos meses ajuda","Salve a dica e mande para outra mãe ou pai.","Amanhã: quando o varo/valgo precisa de atenção. →")],
 [("TER · Na criança","Perna arqueada ou em X: quando é normal","Ontem, o que observar. Hoje, a diferença entre fase do crescimento e causa que pede atenção.","deslize →"),
  ("O comum","O calendário do alinhamento","Arqueada até ~2 anos, leve X por volta dos 3–4, alinhando depois. É a regra na maioria das crianças.","continua →"),
  ("Atenção","O que foge da regra","Muito acentuado, assimétrico, que piora, ou junto com baixa estatura: pode ter uma causa, como raquitismo.","continua →"),
  ("A virada","Tratar a causa alinha","Quando há uma causa, cuidar dela costuma restabelecer o alinhamento. Por isso avaliar importa.","quase lá →"),
  ("Guarde isso","Na dúvida, compare e avalie","Salve e mande para quem tem criança pequena.","Amanhã: “perna torta tem que operar logo”? Mito. →")],
 [("QUA · Mito x Verdade","“Perna torta tem que operar logo”","Ontem, varo e valgo. Hoje, o mito da pressa em corrigir.","deslize →"),
  ("O mito","O que se diz","Que toda perna torta precisa de cirurgia imediata para não “estragar”.","continua →"),
  ("A verdade","A maioria alinha sozinha","Grande parte é fisiológica e se resolve com o tempo. Operar à toa não é cuidado, é exagero.","continua →"),
  ("Quando é real","O que muda a conduta","Casos que não alinham, pioram ou têm causa podem precisar de correção — muitas vezes guiando o crescimento, sem grandes cirurgias.","quase lá →"),
  ("Guarde isso","Nem demais, nem de menos","Salve e mande para quem está em dúvida.","Amanhã: desalinhamento e o joelho do esporte. →")],
 [("QUI · No esporte","Pernas desalinhadas e o esporte","Ontem, o mito. Hoje, como o alinhamento influencia a sobrecarga de quem treina.","deslize →"),
  ("O efeito","O eixo torto sobrecarrega um lado","Quando a perna não está alinhada, o peso se concentra mais de um lado do joelho, e isso pode gerar dor.","continua →"),
  ("O que ajuda","Fortalecer e acompanhar","Boa preparação física distribui melhor a carga. Acompanhar o alinhamento no estirão ajuda a decidir o momento certo.","continua →"),
  ("A virada","Corrigir no tempo certo","Em alguns jovens, alinhar protege a articulação para o esporte e para a vida adulta.","quase lá →"),
  ("Guarde isso","Alinhamento importa no esporte","Salve e mande para um pai de jovem atleta.","Amanhã: como acompanhar o alinhamento no dia a dia. →")],
 [("SEX · No dia a dia","Acompanhar a perna que cresce","Sexta de orientação. Como acompanhar o alinhamento sem ansiedade.","deslize →"),
  ("Como acompanhar","Observar a evolução","O mais importante não é uma foto isolada, e sim como a perna muda ao longo dos meses.","continua →"),
  ("O que registrar","Fotos de frente, em pé","Fotos de frente, pés juntos, ajudam a perceber se está alinhando ou piorando entre as consultas.","continua →"),
  ("A virada","Paciência tem método","Esperar não é “não fazer nada” — é acompanhar de perto e agir na hora certa, se preciso.","quase lá →"),
  ("Guarde isso","Acompanhar é cuidar","Salve a dica das fotos e compartilhe.","Amanhã: quando o desalinhamento precisa de avaliação. →")],
 [("SAB · Quando procurar","Perna torta: quando avaliar","Fim de semana em família. Os sinais de que o desalinhamento precisa de um olhar.","deslize →"),
  ("Sinal 1","Só de um lado","Desalinhamento assimétrico, bem diferente entre as pernas, merece avaliação.","continua →"),
  ("Sinal 2","Que piora com a idade","Em vez de alinhar, está ficando mais torto: vale investigar a causa.","continua →"),
  ("Sinal 3","Com dor ou baixa estatura","Desalinhamento com dor, mancar ou criança que cresce pouco pede avaliação.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve e mande para quem precisa.","Amanhã, o fecho: a correção do eixo — como eu trato. →")],
 [("DOM · Como eu penso","Corrigir o eixo da perna","Fechando a semana: quando o desalinhamento precisa de correção e como penso o tratamento.","deslize →"),
  ("O contexto","Medir antes de tudo","Tratar começa por medir o eixo com precisão e entender a causa — não pela aparência só.","continua →"),
  ("O caminho","Guiar o crescimento ou corrigir","Na criança que ainda cresce, dá para guiar o crescimento com um procedimento pequeno. Em outros casos, correção gradual e acompanhada.","continua →"),
  ("O princípio","Alinhar para proteger","O objetivo nunca é estético — é alinhar para distribuir a carga, proteger a articulação e melhorar a função.","quase lá →"),
  ("Converse comigo","Cada eixo tem um plano","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: Fraturas na criança. →")],
]})

# ===================== SEMANA 6 — FRATURAS NA CRIANÇA =====================
SEASONS.append({"slug":"fraturas","theme":"Semana das Fraturas","days":[
 [("SEG · O que observar","Será que quebrou? O que observar","Esta semana é sobre fraturas na criança. Hoje, os sinais de que pode ser mais que uma pancada.","deslize →"),
  ("Sinais 1 e 2","Dor forte e inchaço num ponto","Dor intensa sobre o osso, inchaço que aumenta e dificuldade de mexer o membro pedem atenção.","continua →"),
  ("Sinal 3","Não usa o braço ou a perna","Criança que protege o membro, não apoia ou não pega as coisas como antes pode ter fratura.","continua →"),
  ("O que engana","Pode não ter roxo","Nem toda fratura incha ou fica roxa de cara. A dor que não passa é o que mais importa.","quase lá →"),
  ("Guarde isso","Na dúvida, imobilize e avalie","Salve e mande para outra família.","Amanhã: por que a fratura da criança é diferente. →")],
 [("TER · Na criança","Por que a fratura infantil é diferente","Ontem, os sinais. Hoje, a placa de crescimento — o que torna o osso da criança especial.","deslize →"),
  ("O que é","Onde o osso cresce","A placa de crescimento é uma área de cartilagem por onde o osso aumenta. É mais frágil que o osso já formado.","continua →"),
  ("Por que importa","A fratura pode passar por ali","Quando a fratura envolve a placa, o acompanhamento é mais cuidadoso para o osso crescer alinhado.","continua →"),
  ("A virada","Criança consolida bem","Por outro lado, a criança costuma colar o osso mais rápido e remodelar pequenos desvios com o crescimento.","quase lá →"),
  ("Guarde isso","Por isso o cuidado é próprio","Salve e mande para quem tem criança ativa.","Amanhã: “criança é elástica, não quebra”? Mito. →")],
 [("QUA · Mito x Verdade","“Criança é elástica, não quebra”","Ontem, a placa de crescimento. Hoje, um mito que atrasa o atendimento.","deslize →"),
  ("O mito","O que se diz","Que osso de criança “só entorta” e que dor depois de cair sempre passa sozinha.","continua →"),
  ("A verdade","Quebra, sim — de outro jeito","A criança tem fraturas próprias, como a “em galho verde”, que podem não ser óbvias e precisam de avaliação.","continua →"),
  ("Quando muda","O sinal que pede raio-X","Dor que não cede, deformidade, não usar o membro ou dor exatamente sobre o osso: avalie.","quase lá →"),
  ("Guarde isso","Na dúvida, não force","Salve e mande para outros pais.","Amanhã: fraturas no esporte, até sem queda. →")],
 [("QUI · No esporte","Fraturas no esporte (até sem queda)","Ontem, o mito. Hoje, as fraturas de quem treina — inclusive as que vêm sem um trauma único.","deslize →"),
  ("O comum","A fratura por estresse","Treino intenso e repetitivo pode trincar o osso aos poucos: dor que piora com a atividade e melhora no repouso.","continua →"),
  ("O alerta","Dor sempre no mesmo ponto","Dor localizada que reaparece a cada treino, mesmo sem “a” pancada, merece avaliação.","continua →"),
  ("A virada","Carga equilibrada protege","Aumentar o treino aos poucos e respeitar o descanso previne boa parte dessas fraturas.","quase lá →"),
  ("Guarde isso","Dor de treino que insiste, avalie","Salve e mande para um pai de jovem atleta.","Amanhã: os primeiros minutos de uma suspeita de fratura. →")],
 [("SEX · Primeiros socorros","Suspeita de fratura: o que fazer","Sexta de guardar para a emergência. Os primeiros minutos diante de uma possível fratura.","deslize →"),
  ("Passo 1","Não tente “colocar no lugar”","Nunca puxe nem endireite o membro. Mantenha a criança calma e o membro como está.","continua →"),
  ("Passo 2","Imobilize e gelo por cima","Apoie o membro com algo rígido e macio, sem apertar. Gelo com pano por cima ajuda na dor.","continua →"),
  ("Sinal de alerta","Quando é urgente","Deformidade visível, osso exposto, dormência ou pé/mão muito pálido: emergência, vá ao pronto-socorro.","quase lá →"),
  ("Guarde isso","Salve para a emergência","Mande para o grupo da escola ou do time.","Amanhã: quando o “torceu” é fratura. →")],
 [("SAB · Quando procurar","Quando o “torceu” é fratura","Fim de semana em família. Os sinais que diferenciam uma torção de uma fratura.","deslize →"),
  ("Sinal 1","Dor exatamente sobre o osso","Dor num ponto do osso (não no músculo) é mais sugestiva de fratura.","continua →"),
  ("Sinal 2","Não apoia nem usa o membro","Não conseguir pisar ou usar o braço, mesmo após algumas horas, pede avaliação.","continua →"),
  ("Sinal 3","Inchaço que aumenta rápido","Inchaço importante e deformidade são sinais de alerta.","quase lá →"),
  ("Guarde isso","Na dúvida, o raio-X tranquiliza","Salve e compartilhe.","Amanhã, o fecho: a fratura que não cola ou consolida torta. →")],
 [("DOM · Como eu penso","Quando a fratura não cola direito","Fechando a semana: a fratura que não consolida ou cola torta — e como penso a solução.","deslize →"),
  ("O contexto","Pseudartrose e desvio","Algumas fraturas demoram a colar (pseudartrose) ou consolidam com um desvio que atrapalha a função.","continua →"),
  ("O caminho","Investigar, estabilizar, estimular","O tratamento investiga a causa, estabiliza o osso e estimula a consolidação — às vezes corrigindo o alinhamento junto.","continua →"),
  ("O princípio","Restaurar a função","O foco é um osso que cole firme e um membro que funcione bem — por etapas, com acompanhamento.","quase lá →"),
  ("Converse comigo","Fratura difícil tem caminho","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: Reconstrução e fixador externo. →")],
]})

# ===================== SEMANA 7 — RECONSTRUÇÃO E FIXADOR =====================
SEASONS.append({"slug":"reconstrucao","theme":"Semana da Reconstrução","days":[
 [("SEG · O que observar","Quando pensar em reconstrução óssea","Esta semana é sobre reconstrução e fixador externo. Hoje, os sinais de que um osso precisa de mais.","deslize →"),
  ("Sinal 1","Deformidade que atrapalha a função","Osso ou membro torto que afeta andar, calçar ou usar a mão, e que não melhora, pode precisar de correção.","continua →"),
  ("Sinal 2","Diferença de comprimento que aumenta","Uma perna que vai ficando mais curta, mancar ou desnivelar o quadril merece avaliação.","continua →"),
  ("Sinal 3","Sequela de fratura ou infecção","Osso que não colou, que cola torto ou ficou frágil após infecção pode ser reconstruído.","quase lá →"),
  ("Guarde isso","Reconstrução tem indicação","Salve e mande para quem convive com isso.","Amanhã: diferença de comprimento entre as pernas. →")],
 [("TER · Na criança","Uma perna mais curta que a outra","Ontem, os sinais. Hoje, a diferença de comprimento — quando observar e quando agir.","deslize →"),
  ("O comum","Pequenas diferenças são normais","Quase todo mundo tem uma perna milímetros diferente da outra. Pequenas diferenças costumam ser bem toleradas.","continua →"),
  ("Quando importa","As que aumentam","Diferenças maiores, que crescem com a criança ou vêm de fratura, infecção ou doença, merecem acompanhamento.","continua →"),
  ("As opções","Da palmilha à correção","O caminho depende do tamanho da diferença, da causa, da idade e da função — da palmilha a procedimentos no osso.","quase lá →"),
  ("Guarde isso","Avaliar cedo abre opções","Salve e mande para quem precisa.","Amanhã: “fixador é a última opção”? Mito. →")],
 [("QUA · Mito x Verdade","“Fixador externo é a última opção”","Ontem, a discrepância. Hoje, o mito sobre o aparelho que assusta os pais.","deslize →"),
  ("O mito","O que se imagina","Que o fixador é só sofrimento, prende a pessoa na cama e é sinal de caso perdido.","continua →"),
  ("A verdade","É uma ferramenta poderosa","O fixador permite corrigir deformidades e tratar ossos difíceis com a pessoa andando, indo à escola e ao trabalho.","continua →"),
  ("O contexto","Assusta, mas a rotina é simples","Com poucos cuidados, a vida segue. O incômodo inicial dá lugar a uma rotina viável.","quase lá →"),
  ("Guarde isso","Mito desfeito","Salve e mande para quem vai começar um tratamento.","Amanhã: como é viver com o fixador. →")],
 [("QUI · No dia a dia","Viver com o fixador no dia a dia","Ontem, o mito. Hoje, como é a rotina de quem está com o aparelho.","deslize →"),
  ("O que dá para fazer","Escola, trabalho e banho","Em geral dá para ir à escola e ao trabalho e tomar banho, seguindo as orientações de apoio e higiene.","continua →"),
  ("O apoio","Andar é parte do tratamento","Apoiar o quanto foi combinado e movimentar ajudam o osso e a recuperação. A fisioterapia entra junto.","continua →"),
  ("O emocional","O começo é o mais difícil","As primeiras semanas assustam; depois vira rotina. Falar das dúvidas com a equipe faz muita diferença.","quase lá →"),
  ("Guarde isso","A vida segue com o fixador","Salve e mande para quem está nessa fase.","Amanhã: os cuidados com os pinos. →")],
 [("SEX · Cuidados","Fixador: cuidando dos pinos","Sexta de orientação prática. Os cuidados que fazem parte do tratamento com fixador.","deslize →"),
  ("Cuidado 1","Limpo e seco","Manter a região dos pinos limpa e seca, conforme a orientação individual, é o básico do dia a dia.","continua →"),
  ("Cuidado 2","Observar a pele","Vermelhidão, dor nova, calor ou secreção ao redor de um pino merecem atenção e aviso à equipe.","continua →"),
  ("Cuidado 3","Não mexer na montagem","Não aperte nem mexa nas peças por conta própria; siga o apoio combinado e os retornos.","quase lá →"),
  ("Guarde isso","Suas orientações valem mais","Salve e compartilhe com quem usa fixador.","Amanhã: quando avisar a equipe sem demora. →")],
 [("SAB · Quando procurar","Fixador: quando avisar sem demora","Fim de semana em família. Os sinais que pedem contato com a equipe.","deslize →"),
  ("Sinal 1","Secreção ou vermelhidão que aumenta","Pino com secreção, calor e vermelhidão crescente pode ser infecção começando.","continua →"),
  ("Sinal 2","Febre ou dor nova e forte","Febre junto com dor nova no membro merece avaliação sem esperar o próximo retorno.","continua →"),
  ("Sinal 3","Dedo frio, pálido ou dormente","Mudança de cor, frieza ou dormência no pé ou na mão é sinal de alerta.","quase lá →"),
  ("Guarde isso","Na dúvida, avise","Salve e mande para quem convive com fixador.","Amanhã, o fecho: a reconstrução por etapas. →")],
 [("DOM · Como eu penso","Reconstruir osso por etapas","Fechando a semana: como o corpo regenera osso e por que o tratamento é em fases.","deslize →"),
  ("O que é","O corpo cria osso novo","Após um corte ósseo planejado, o próprio corpo forma osso no espaço que vai sendo aberto, aos poucos.","continua →"),
  ("As fases","Espera, distração e consolidação","Um tempo de espera; depois o afastamento gradual, milímetro a milímetro; por fim, o osso novo endurece.","continua →"),
  ("O princípio","Função, nunca estética","Reconstruir é corrigir deformidade, igualar comprimento e devolver função — jamais por aparência ou altura.","quase lá →"),
  ("Converse comigo","Cada osso tem um plano","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: Dores do crescimento e queixas comuns. →")],
]})

# ===================== SEMANA 8 — DORES DO CRESCIMENTO =====================
SEASONS.append({"slug":"crescimento","theme":"Semana das Dores do Crescimento","days":[
 [("SEG · O que observar","Dor nas pernas à noite: o que observar","Esta semana é sobre as dores do crescimento. Hoje, o que olhar quando a criança reclama à noite.","deslize →"),
  ("O padrão comum","Nas duas pernas, fim do dia","A dor do crescimento costuma vir no fim do dia ou à noite, nas duas pernas, e melhora pela manhã.","continua →"),
  ("O que alivia","Massagem e carinho ajudam","Massagear, aquecer e acolher costumam aliviar. No dia seguinte, a criança brinca normal.","continua →"),
  ("O contraste","O que NÃO é dor de crescimento","Dor só de um lado, com inchaço, que faz mancar ou que aparece de dia, é outra coisa.","quase lá →"),
  ("Guarde isso","Conhecer o padrão tranquiliza","Salve e mande para outra mãe ou pai.","Amanhã: afinal, o que é a dor de crescimento? →")],
 [("TER · Na criança","O que é a dor de crescimento","Ontem, o padrão. Hoje, o que se sabe sobre essa dor tão comum.","deslize →"),
  ("O que é","Comum e benigna","Atinge muitas crianças em idade pré-escolar e escolar. Não deixa sequela e não é sinal de doença na maioria.","continua →"),
  ("De onde vem","Não é do osso crescendo","Apesar do nome, não é o osso “doendo para crescer”. Tem a ver com o dia ativo e a sensibilidade da criança.","continua →"),
  ("A virada","Diagnóstico é pelo padrão","Não há exame que “prove”. O médico reconhece pelo padrão típico e descarta o que precisa de atenção.","quase lá →"),
  ("Guarde isso","Benigna, mas vale conhecer","Salve e mande para quem tem criança pequena.","Amanhã: “dor de crescimento não existe”? Mito. →")],
 [("QUA · Mito x Verdade","“Dor de crescimento é invenção”","Ontem, o que é. Hoje, o mito que confunde os dois lados.","deslize →"),
  ("Os dois extremos","Existe x explica tudo","Tem quem diga que não existe; e quem use o nome para qualquer dor. Os dois extremos atrapalham.","continua →"),
  ("A verdade","Existe — e tem limites","A dor de crescimento é real e benigna, mas só algumas dores se encaixam nela. As outras precisam de olhar.","continua →"),
  ("O cuidado","Nome certo, conduta certa","Chamar tudo de “crescimento” pode atrasar o diagnóstico do que é diferente.","quase lá →"),
  ("Guarde isso","Nem nega, nem explica tudo","Salve e mande para outros pais.","Amanhã: dor após o esporte x dor de crescimento. →")],
 [("QUI · No esporte","Dor após o treino ou de crescimento?","Ontem, o mito. Hoje, como diferenciar a dor do esporte da dor de crescimento.","deslize →"),
  ("A do esporte","Ligada à atividade","A dor do esporte costuma estar num ponto, ligada ao treino, e melhora com ajuste de carga e descanso.","continua →"),
  ("A do crescimento","Difusa e noturna","A de crescimento é difusa, nas duas pernas, à noite, sem relação clara com “o” treino.","continua →"),
  ("A virada","Ponto fixo de dor = avaliar","Dor sempre no mesmo ponto, que piora com a atividade, merece avaliação.","quase lá →"),
  ("Guarde isso","Saber diferenciar ajuda","Salve e mande para um pai de jovem atleta.","Amanhã: o que fazer na crise de dor à noite. →")],
 [("SEX · Primeiros socorros","Crise de dor à noite: o que fazer","Sexta de orientação. Como acolher a criança na hora da dor de crescimento.","deslize →"),
  ("Passo 1","Calor e massagem","Compressa morna e massagem na perna costumam aliviar bem na hora.","continua →"),
  ("Passo 2","Acolher sem alarmar","Ficar perto, conversar e tranquilizar ajuda — a criança sente a sua calma.","continua →"),
  ("Atenção","O que muda a noite","Se a dor é só de um lado, com inchaço, febre ou faz mancar de manhã, não trate como “crescimento”: avalie.","quase lá →"),
  ("Guarde isso","Acolhimento é parte do alívio","Salve e compartilhe com quem precisa.","Amanhã: quando a dor nas pernas pede avaliação. →")],
 [("SAB · Quando procurar","Dor nas pernas: quando avaliar","Fim de semana em família. Os sinais de que a dor não é só do crescimento.","deslize →"),
  ("Sinal 1","Só de um lado / ponto fixo","Dor sempre no mesmo lugar, de um lado só, merece avaliação.","continua →"),
  ("Sinal 2","Inchaço, mancar ou febre","Dor com inchaço, vermelhidão, febre ou que faz mancar é diferente.","continua →"),
  ("Sinal 3","Que atrapalha o dia","Dor que limita o brincar, que acorda toda noite ou que vem com cansaço fora do normal: avalie.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve e compartilhe.","Amanhã, o fecho: a dor que insiste — como eu penso. →")],
 [("DOM · Como eu penso","A dor que insiste: o que eu penso","Fechando a semana: quando a dor não some e como conduzo a investigação.","deslize →"),
  ("O contexto","Quando sai do padrão","Dor persistente, localizada, com sinais de alerta, sai do quadro benigno e pede olhar mais atento.","continua →"),
  ("O caminho","Investigar com calma e critério","História cuidadosa, exame e, quando necessário, alguns exames direcionados ajudam a entender a causa.","continua →"),
  ("O princípio","Tranquilizar e cuidar","Na maioria, a investigação serve para tranquilizar; quando há algo, encontrar cedo faz diferença.","quase lá →"),
  ("Converse comigo","Dor que preocupa tem caminho","Avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: Esporte no adolescente. →")],
]})

# ===================== SEMANA 9 — ESPORTE NO ADOLESCENTE =====================
SEASONS.append({"slug":"esporte","theme":"Semana do Esporte Jovem","days":[
 [("SEG · O que observar","Dores do jovem atleta: o que observar","Esta semana é sobre esporte no adolescente. Hoje, os sinais nas dores de quem treina.","deslize →"),
  ("Sinal 1","Dor que piora com o treino","Dor ligada à atividade, que melhora no descanso, costuma ser sobrecarga — mas vale ficar de olho.","continua →"),
  ("Sinal 2","Dor que muda o jeito de jogar","Quando a dor faz mancar, poupar um lado ou cair o rendimento, merece atenção.","continua →"),
  ("O equilíbrio","Treino x descanso","Crescer e treinar ao mesmo tempo pede equilíbrio. Descanso também é treino.","quase lá →"),
  ("Guarde isso","Ouvir o corpo do atleta","Salve e mande para um pai de jovem atleta.","Amanhã: dor no calcanhar de quem corre. →")],
 [("TER · Na criança","Dor no calcanhar em quem treina","Ontem, os sinais. Hoje, a doença de Sever — comum no calcanhar do jovem atleta.","deslize →"),
  ("O que é","Na área de crescimento","É uma inflamação na placa de crescimento do calcanhar, por tração e impacto repetidos no estirão.","continua →"),
  ("O que ajuda","Carga, gelo e alongamento","Equilibrar o treino, gelo após a atividade e alongar a panturrilha costumam aliviar.","continua →"),
  ("A virada","Costuma passar","Tende a melhorar com o fim do crescimento. O acompanhamento evita que limite o esporte.","quase lá →"),
  ("Guarde isso","Dor que limita, avalie","Salve e mande para o time.","Amanhã: “dor faz parte do esporte”? Mito. →")],
 [("QUA · Mito x Verdade","“Dor faz parte, é só aguentar”","Ontem, o Sever. Hoje, o mito mais perigoso do esporte jovem.","deslize →"),
  ("O mito","No pain, no gain","A ideia de que toda dor é sinal de evolução e que parar é “fraqueza”.","continua →"),
  ("A verdade","Dor é aviso, não troféu","Dor que persiste, que muda o movimento ou que volta sempre é sinal de sobrecarga ou lesão — não de progresso.","continua →"),
  ("O cuidado","Respeitar a dor protege a carreira","Ignorar a dor é a receita para a lesão que afasta de verdade.","quase lá →"),
  ("Guarde isso","Dor que insiste não é frescura","Salve e mande para treinadores e pais.","Amanhã: sobrecarga e a importância do descanso. →")],
 [("QUI · No esporte","Sobrecarga: quando o treino vira lesão","Ontem, o mito. Hoje, a sobrecarga — a lesão silenciosa do jovem atleta.","deslize →"),
  ("O que é","Repetição sem descanso","Treinar demais, sem recuperação, faz microlesões se acumularem até virar dor e lesão.","continua →"),
  ("Os sinais","Queda de rendimento e dor que volta","Cansaço fora do normal, piora no desempenho e dor recorrente são alertas de sobrecarga.","continua →"),
  ("A virada","Periodizar e dormir bem","Variar estímulos, respeitar folgas e dormir bem são tão importantes quanto o treino.","quase lá →"),
  ("Guarde isso","Descanso é parte do esporte","Salve e mande para o grupo do time.","Amanhã: estiramento muscular — primeiros minutos. →")],
 [("SEX · Primeiros socorros","Estiramento muscular: o que fazer","Sexta de guardar para a emergência. Os primeiros minutos de uma lesão muscular.","deslize →"),
  ("Passo 1","Pare na hora","Sentiu “a fisgada”? Pare. Continuar transforma um estiramento leve em lesão maior.","continua →"),
  ("Passo 2","Gelo, repouso e elevar","Gelo com pano, repouso e elevar o membro nas primeiras horas. Nada de massagem forte ou calor agora.","continua →"),
  ("Sinal de alerta","Quando avaliar","Dor forte, “buraco” no músculo, perda de força ou hematoma grande pedem avaliação.","quase lá →"),
  ("Guarde isso","Salve para a emergência","Mande para o time e a comissão técnica.","Amanhã: dor do esporte que precisa de avaliação. →")],
 [("SAB · Quando procurar","Dor do esporte: quando avaliar","Fim de semana em família. Os sinais de que a dor do treino precisa de um olhar.","deslize →"),
  ("Sinal 1","Não passa com descanso","Dor que persiste mesmo parando o treino por dias merece avaliação.","continua →"),
  ("Sinal 2","Incha ou trava a articulação","Inchaço repetido, travamento ou sensação de falsear não são da sobrecarga simples.","continua →"),
  ("Sinal 3","Volta sempre no mesmo ponto","Dor localizada que reaparece a cada treino pode ser fratura por estresse ou apofisite.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve e compartilhe.","Amanhã, o fecho: a lesão que volta e o retorno seguro. →")],
 [("DOM · Como eu penso","A lesão que volta sempre","Fechando a semana: por que algumas lesões insistem e como penso o retorno seguro.","deslize →"),
  ("O contexto","Voltar cedo demais","A causa mais comum de recidiva é retornar antes de recuperar força, amplitude e confiança.","continua →"),
  ("O caminho","Critérios, não só calendário","O retorno se baseia em testes de força, equilíbrio e gesto esportivo — não só em “quantas semanas passaram”.","continua →"),
  ("O princípio","Reabilitar para durar","Tratar a causa e reabilitar bem protege o atleta para a temporada e para a vida.","quase lá →"),
  ("Converse comigo","Lesão que insiste tem caminho","Avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: a Marcha e o pé que anda. →")],
]})

# ===================== SEMANA 10 — MARCHA E O PÉ =====================
SEASONS.append({"slug":"marcha","theme":"Semana da Marcha e do Pé","days":[
 [("SEG · O que observar","O jeito de andar: o que observar","Esta semana é sobre a marcha e o pé. Hoje, o que olhar no andar — e o que costuma ser fase.","deslize →"),
  ("Sinal 1","Cai demais ou cansa rápido","Quedas frequentes, tropeços e cansaço acima do normal ao andar merecem atenção.","continua →"),
  ("Sinal 2","Anda diferente de um lado","Mancar, arrastar um pé ou usar um lado bem diferente do outro vale avaliar.","continua →"),
  ("O que costuma ser fase","Pés para dentro ou para fora","Muito comum nos primeiros anos e costuma melhorar. O exagero ou a assimetria é que chamam atenção.","quase lá →"),
  ("Guarde isso","Observar o andar ajuda","Salve e mande para outra mãe ou pai.","Amanhã: pés para dentro — é problema? →")],
 [("TER · Na criança","Pés para dentro: precisa corrigir?","Ontem, o andar. Hoje, a queixa clássica: a criança que anda com os pés virados para dentro.","deslize →"),
  ("O comum","Faz parte do desenvolvimento","Na maioria, vem da rotação natural dos ossos da perna e do pé, e melhora sozinho com o crescimento.","continua →"),
  ("O que não ajuda","Botinha e palmilha mágicas","Calçados especiais e órteses, na maioria dos casos, não mudam a evolução. O tempo costuma resolver.","continua →"),
  ("Atenção","Quando avaliar","Muito acentuado, só de um lado, que piora, com quedas frequentes ou dor: vale avaliar.","quase lá →"),
  ("Guarde isso","Na maioria, é só acompanhar","Salve e mande para quem está preocupado.","Amanhã: “criança precisa de sapato firme”? Mito. →")],
 [("QUA · Mito x Verdade","“Bebê precisa de sapato firme”","Ontem, os pés para dentro. Hoje, o mito do calçado.","deslize →"),
  ("O mito","O que se diz","Que o pé precisa de sapato rígido “que segura o tornozelo” para se formar direito.","continua →"),
  ("A verdade","Descalço fortalece","Andar descalço em casa, em segurança, fortalece o pé. O sapato é proteção — prefira solado flexível.","continua →"),
  ("O que importa","Tamanho e flexibilidade","Sapato no tamanho certo, leve e que dobra na frente é melhor que o “durão”.","quase lá →"),
  ("Guarde isso","Pé livre é pé forte","Salve e mande para os avós também.","Amanhã: pé cavo e a sobrecarga no esporte. →")],
 [("QUI · No esporte","Pé cavo: o arco alto que sobrecarrega","Ontem, o sapato. Hoje, o pé com arco muito alto — e o que muda no esporte.","deslize →"),
  ("O que é","O oposto do pé chato","No pé cavo, o arco é mais alto que o habitual e o peso se concentra em poucos pontos.","continua →"),
  ("No esporte","Mais bolhas, entorses e dor","Essa concentração de carga pode dar dor, calos e mais tendência a torcer o tornozelo.","continua →"),
  ("Quando investigar","Acentuado ou que piora","Pé cavo importante, que progride ou vem com formigamento, merece avaliação da causa.","quase lá →"),
  ("Guarde isso","Arco alto também merece olhar","Salve e mande para um pai de jovem atleta.","Amanhã: como escolher o calçado da criança. →")],
 [("SEX · Primeiros socorros","Escolhendo o calçado da criança","Sexta de orientação. Como escolher um sapato que ajuda o pé que cresce.","deslize →"),
  ("Dica 1","Meça o pé, não o sapato antigo","Crianças crescem rápido; meça o pé de vez em quando e deixe uma folga à frente.","continua →"),
  ("Dica 2","Leve e flexível","Prefira solado que dobra na frente, leve e firme no calcanhar — sem ser rígido.","continua →"),
  ("Dica 3","Nem apertado, nem grande demais","Apertado machuca; grande demais faz tropeçar. O ponto certo é uma folga de um dedo.","quase lá →"),
  ("Guarde isso","Salve para a próxima compra","Mande para outra família.","Amanhã: quando o jeito de andar precisa de avaliação. →")],
 [("SAB · Quando procurar","Marcha alterada: quando avaliar","Fim de semana em família. Os sinais de que o jeito de andar pede um olhar.","deslize →"),
  ("Sinal 1","Anda na ponta dos pés sempre","Andar só na ponta, o tempo todo e depois dos 2–3 anos, merece avaliação.","continua →"),
  ("Sinal 2","Assimetria ou piora","Andar bem diferente de um lado, ou que piora em vez de melhorar, vale investigar.","continua →"),
  ("Sinal 3","Com quedas e atraso","Marcha com muitas quedas, atraso para andar ou perda de habilidades já conquistadas: avalie.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve e compartilhe.","Amanhã, o fecho: a marcha que esconde uma causa. →")],
 [("DOM · Como eu penso","Quando a marcha tem uma causa","Fechando a semana: quando o jeito de andar aponta para algo que precisa de cuidado.","deslize →"),
  ("O contexto","Da ponta dos pés ao neurológico","Andar na ponta que persiste, assimetria ou atraso podem ter causas que vão do encurtamento a questões neurológicas.","continua →"),
  ("O caminho","Avaliar a criança inteira","Olho não só o pé: postura, força, reflexos e desenvolvimento — para entender a marcha de verdade.","continua →"),
  ("O princípio","Cuidar cedo, andar melhor","Quando há uma causa, agir no tempo certo melhora a função e o dia a dia da criança.","quase lá →"),
  ("Converse comigo","Toda marcha tem uma história","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: Cotovelo e braço. →")],
]})

# ===================== SEMANA 11 — COTOVELO E BRAÇO =====================
SEASONS.append({"slug":"cotovelo","theme":"Semana do Cotovelo e Braço","days":[
 [("SEG · O que observar","Dor no braço da criança: o que observar","Esta semana é sobre cotovelo e braço. Hoje, o que olhar quando a criança reclama do braço.","deslize →"),
  ("Sinal 1","Não usa o braço normalmente","Criança que para de usar o braço, não pega as coisas ou protege o cotovelo merece atenção.","continua →"),
  ("Sinal 2","Dor após cair sobre a mão","Queda com a mão espalmada é causa comum de fratura no cotovelo e no punho.","continua →"),
  ("O que observar","Inchaço e posição","Inchaço no cotovelo, braço “preso” numa posição ou deformidade pedem avaliação.","quase lá →"),
  ("Guarde isso","Braço que não funciona, avalie","Salve e mande para outra família.","Amanhã: o “cotovelo de babá”. →")],
 [("TER · Na criança","Cotovelo de babá: o que é","Ontem, os sinais. Hoje, a clássica pronação dolorosa — o “cotovelo de babá”.","deslize →"),
  ("Como acontece","Um puxão no bracinho","Acontece quando se puxa a criança pequena pela mão ou pelo braço. Um ligamento “escorrega” no cotovelo.","continua →"),
  ("O sinal","Para de mexer o braço","A criança chora, deixa o braço esticado ao lado do corpo e não quer mexer — sem inchaço aparente.","continua →"),
  ("O que fazer","Não puxe nem force","Não tente resolver puxando. A redução é simples, mas deve ser feita por quem sabe, após avaliar.","quase lá →"),
  ("Guarde isso","Evite puxar pelo braço","Salve e mande para pais e avós.","Amanhã: “clavícula quebrada precisa de cirurgia”? Mito. →")],
 [("QUA · Mito x Verdade","“Clavícula quebrada? Tem que operar”","Ontem, o cotovelo de babá. Hoje, o mito da fratura de clavícula.","deslize →"),
  ("O mito","O que se pensa","Que toda clavícula quebrada na criança precisa de cirurgia e parafusos.","continua →"),
  ("A verdade","A maioria cola sozinha","Na criança, a clavícula costuma consolidar muito bem só com tipoia e tempo. Cirurgia é exceção.","continua →"),
  ("O caroço","O calo ósseo assusta, mas some","Pode aparecer um caroço no local enquanto o osso cola; costuma diminuir e remodelar com o crescimento.","quase lá →"),
  ("Guarde isso","Nem toda fratura opera","Salve e mande para outros pais.","Amanhã: o cotovelo de quem arremessa e treina. →")],
 [("QUI · No esporte","O cotovelo de quem treina","Ontem, a clavícula. Hoje, o cotovelo sobrecarregado no esporte (arremesso, ginástica).","deslize →"),
  ("O que é","Tração repetida no crescimento","Lançar, apoiar o peso ou repetir o gesto sobrecarrega as áreas de crescimento do cotovelo do jovem.","continua →"),
  ("Os sinais","Dor na parte de dentro ou de fora","Dor no cotovelo que piora com o gesto esportivo e melhora com descanso merece atenção.","continua →"),
  ("A virada","Técnica e carga importam","Ajustar volume de arremessos, técnica e descanso previne lesões que podem ser sérias nessa fase.","quase lá →"),
  ("Guarde isso","Dor no cotovelo do atleta, avalie","Salve e mande para treinadores.","Amanhã: caiu sobre o braço — primeiros minutos. →")],
 [("SEX · Primeiros socorros","Caiu sobre a mão ou o braço: e agora?","Sexta de guardar para a emergência. Os primeiros minutos após uma queda sobre o braço.","deslize →"),
  ("Passo 1","Não force o movimento","Não tente esticar nem “testar” o braço. Mantenha como está e acalme a criança.","continua →"),
  ("Passo 2","Tipoia improvisada e gelo","Apoie o braço junto ao corpo (tipoia improvisada) e gelo com pano por cima, sem apertar.","continua →"),
  ("Sinal de alerta","Quando é urgente","Deformidade, muito inchaço, dormência ou mão pálida/fria: pronto-socorro sem demora.","quase lá →"),
  ("Guarde isso","Salve para a emergência","Mande para o grupo da escola.","Amanhã: o cotovelo inchado que pede avaliação rápida. →")],
 [("SAB · Quando procurar","Cotovelo após queda: quando avaliar","Fim de semana em família. Por que o cotovelo da criança merece atenção especial.","deslize →"),
  ("Sinal 1","Muito inchado e dolorido","Cotovelo bem inchado, que a criança não estica nem dobra, pede avaliação.","continua →"),
  ("Sinal 2","Não usa a mão direito","Dormência, formigamento ou dificuldade de mexer os dedos é sinal de alerta.","continua →"),
  ("Por quê","Fratura de cotovelo pede cuidado","Algumas fraturas de cotovelo precisam de tratamento rápido para o osso crescer alinhado.","quase lá →"),
  ("Guarde isso","Cotovelo inchado, não espere demais","Salve e compartilhe.","Amanhã, o fecho: o cotovelo que colou torto — como eu trato. →")],
 [("DOM · Como eu penso","Quando o cotovelo cola torto","Fechando a semana: a fratura de cotovelo que consolida desalinhada — e como penso a correção.","deslize →"),
  ("O contexto","Desvio que atrapalha","Algumas fraturas, se não bem alinhadas, deixam o cotovelo torto ou com movimento limitado.","continua →"),
  ("O caminho","Corrigir o eixo e a função","Dá para planejar e corrigir o alinhamento, recuperando o movimento e o uso do braço.","continua →"),
  ("O princípio","Movimento e uso primeiro","O objetivo é um braço que dobra, estica e funciona bem no dia a dia.","quase lá →"),
  ("Converse comigo","Cotovelo difícil tem caminho","Casos complexos têm avaliação cuidadosa e plano realista. WhatsApp na bio.","Semana que vem: Primeiros Socorros — o guia. →")],
]})

# ===================== SEMANA 12 — PRIMEIROS SOCORROS (guia) =====================
SEASONS.append({"slug":"socorros","theme":"Semana dos Primeiros Socorros","days":[
 [("SEG · O que observar","O que toda família deveria saber","Esta semana é um guia rápido de primeiros socorros ortopédicos. Hoje, o princípio que vale para tudo.","deslize →"),
  ("Princípio 1","Proteger antes de tudo","Diante de dor após trauma: pare a atividade, proteja o membro e não force o movimento para “testar”.","continua →"),
  ("Princípio 2","Gelo, elevar, observar","Gelo com pano, elevar o membro e observar a evolução resolvem boa parte das lesões leves.","continua →"),
  ("Princípio 3","Na dúvida, imobilize e avalie","Se há sinal de fratura, imobilize como está e procure avaliação. Não puxe nem endireite.","quase lá →"),
  ("Guarde isso","Salve este guia da semana","Mande para a sua família.","Amanhã: queda — quando a altura preocupa. →")],
 [("TER · Na criança","Criança caiu: quando preocupa","Ontem, os princípios. Hoje, a queda do dia a dia — o que muda a urgência.","deslize →"),
  ("A queda comum","Da própria altura","A maioria das quedas da própria altura assusta mais que machuca. Observar costuma bastar.","continua →"),
  ("O que pesa","Altura e como caiu","Quedas de altura (cama elástica, beliche, escada) ou sobre a mão/cotovelo têm mais risco de fratura.","continua →"),
  ("Atenção","Membro que não funciona","Se a criança não usa o braço ou a perna, ou há deformidade, avalie.","quase lá →"),
  ("Guarde isso","Como caiu importa","Salve e mande para outra família.","Amanhã: gelo ou calor? O mito. →")],
 [("QUA · Mito x Verdade","Gelo ou calor? E “pôr no lugar”?","Ontem, as quedas. Hoje, os mitos que mais atrapalham no socorro.","deslize →"),
  ("Mito 1","Calor nas primeiras horas","Nas primeiras 48h de um trauma, é gelo. Calor é para tensão muscular crônica, não para a lesão recente.","continua →"),
  ("Mito 2","“Pôr o osso no lugar”","Nunca tente reduzir fratura ou luxação em casa. Pode piorar. Imobilize e leve para avaliar.","continua →"),
  ("Mito 3","Massagear na hora","Massagem forte logo após o trauma aumenta o inchaço. O certo é proteger e gelar.","quase lá →"),
  ("Guarde isso","Mitos esclarecidos","Salve e mande para quem cuida de criança.","Amanhã: conduta na lesão durante o jogo. →")],
 [("QUI · No esporte","Lesão durante o jogo: o que fazer","Ontem, os mitos. Hoje, a conduta no campo ou na quadra.","deslize →"),
  ("Passo 1","Tire de campo e avalie","Dor que faz parar não se “corre para passar”. Tire o atleta, observe e não force o retorno.","continua →"),
  ("Passo 2","Gelo e imobilize se preciso","Gelo com pano; se há sinal de fratura ou luxação, imobilize como está.","continua →"),
  ("O kit básico","Gelo, faixa e bom senso","Um kit simples (gelo instantâneo, faixa, tipoia) e calma resolvem o primeiro momento.","quase lá →"),
  ("Guarde isso","Salve para a comissão técnica","Mande para o grupo do time.","Amanhã: o passo a passo da torção, fratura e luxação. →")],
 [("SEX · Primeiros socorros","Torção, fratura ou luxação: passo a passo","Sexta de guardar para a emergência. Um resumo prático para os três casos.","deslize →"),
  ("Torção","Proteger, gelo, elevar","Pare, gelo com pano por 15 min, eleve e evite forçar o apoio nas primeiras horas.","continua →"),
  ("Suspeita de fratura","Imobilizar como está","Não endireite. Apoie com algo rígido e macio, gelo por cima e procure avaliação.","continua →"),
  ("Luxação","Não tente reduzir","Articulação “fora do lugar” é emergência: imobilize na posição e vá ao pronto-socorro.","quase lá →"),
  ("Guarde isso","Salve o resumo dos três","Mande para a sua família.","Amanhã: os sinais de ir ao pronto-socorro. →")],
 [("SAB · Quando procurar","Quando ir ao pronto-socorro","Fim de semana em família. Os sinais que pedem atendimento sem esperar.","deslize →"),
  ("Sinal 1","Deformidade ou osso exposto","Membro torto, deformidade visível ou ferida com osso aparecendo: emergência.","continua →"),
  ("Sinal 2","Não apoia / não usa o membro","Não conseguir pisar ou usar o braço, com dor importante, pede avaliação no mesmo dia.","continua →"),
  ("Sinal 3","Dormência, palidez ou frieza","Dedo ou membro dormente, pálido ou frio é sinal de alerta — vá logo.","quase lá →"),
  ("Guarde isso","Na dúvida, avalie","Salve e compartilhe.","Amanhã, o fecho: o que levar e o que esperar da avaliação. →")],
 [("DOM · Como eu penso","Depois do susto: o que levar à consulta","Fechando a semana: como tirar o melhor da avaliação ortopédica.","deslize →"),
  ("O que levar","História e exames anteriores","Como aconteceu, há quanto tempo, exames que já tem (mesmo antigos) e as suas dúvidas anotadas.","continua →"),
  ("O que esperar","Exame primeiro, imagem se mudar a conduta","O exame clínico vem antes. Raio-X ou outros exames entram quando mudam a decisão.","continua →"),
  ("O princípio","Decidir junto, com calma","Boa avaliação explica o que é, o que fazer e o que observar — sem alarme e sem pressa.","quase lá →"),
  ("Converse comigo","Da emergência ao acompanhamento","Se precisar de avaliação ou segunda opinião, WhatsApp na bio.","Semana que vem: Casos complexos e reconstrução. →")],
]})

# ===================== SEMANA 13 — CASOS COMPLEXOS (fecho) =====================
SEASONS.append({"slug":"complexos","theme":"Semana dos Casos Complexos","days":[
 [("SEG · O que observar","Quando procurar um especialista em casos complexos","Esta semana é sobre casos complexos e reconstrução. Hoje, os sinais de que vale uma avaliação especializada.","deslize →"),
  ("Sinal 1","Problema que não se resolve","Deformidade, fratura ou osso difícil que já passou por tratamentos sem solução merece um novo olhar.","continua →"),
  ("Sinal 2","Vários cuidados ao mesmo tempo","Casos que envolvem mais de uma área (ossos, músculos, neuro) se beneficiam de um plano integrado.","continua →"),
  ("Sinal 3","Em crianças e adultos","Reconstrução e correção de deformidades complexas valem em qualquer idade — sempre olhando a função.","quase lá →"),
  ("Guarde isso","Caso difícil não é caso perdido","Salve e mande para quem precisa.","Amanhã: deformidades de causa neurológica. →")],
 [("TER · Na criança","Deformidades de causa neurológica","Ontem, quando procurar. Hoje, quando o equilíbrio muscular muda e afeta os ossos.","deslize →"),
  ("O contexto","PC, mielomeningocele e outras","Condições como paralisia cerebral e mielomeningocele podem levar a deformidades em pés, quadris e membros ao crescer.","continua →"),
  ("O cuidado","Em equipe e por etapas","Acompanhar o crescimento, prevenir deformidades e corrigir o que atrapalha sentar, ficar de pé ou andar.","continua →"),
  ("O objetivo","Função e conforto","Mais do que um ideal, o foco é o que melhora a rotina, o posicionamento e a qualidade de vida.","quase lá →"),
  ("Guarde isso","A ortopedia também ajuda aqui","Salve e mande para quem convive com isso.","Amanhã: “não há mais o que fazer”? Mito. →")],
 [("QUA · Mito x Verdade","“Já disseram que não há o que fazer”","Ontem, as deformidades neurológicas. Hoje, talvez o mito mais importante da semana.","deslize →"),
  ("O mito","O caso perdido","A ideia de que, ouvido um “não tem solução”, acabaram as opções.","continua →"),
  ("A verdade","Quase sempre há um caminho","Em casos complexos, costuma valer um segundo olhar. Nem sempre é cura, mas muitas vezes há como melhorar a função.","continua →"),
  ("O cuidado","Expectativa realista, sem promessa","Caminho não é milagre. É avaliar com honestidade o que dá para melhorar e a que custo.","quase lá →"),
  ("Guarde isso","Vale um segundo olhar","Salve e mande para quem precisa de esperança realista.","Amanhã: e para quem é de fora de SP? →")],
 [("QUI · De longe","Mora longe? Dá para começar à distância","Ontem, o segundo olhar. Hoje, como ajudo quem é de fora de São Paulo.","deslize →"),
  ("O que dá","Orientar e organizar o caminho","Por telemedicina dá para ouvir o caso, revisar exames e organizar os próximos passos.","continua →"),
  ("O limite","Exame presencial tem hora","Parte da avaliação e os procedimentos são presenciais — a distância ajuda a planejar e a não perder tempo.","continua →"),
  ("A virada","Menos viagens desnecessárias","Organizar antes evita deslocamentos à toa e deixa a vinda mais objetiva.","quase lá →"),
  ("Guarde isso","Distância não precisa ser barreira","Salve e mande para quem é de fora.","Amanhã: como é o acompanhamento por etapas. →")],
 [("SEX · O acompanhamento","Como é o tratamento por etapas","Sexta de orientação. O que esperar de um acompanhamento de caso complexo.","deslize →"),
  ("Etapa 1","Avaliar e planejar","Tudo começa com uma avaliação cuidadosa e um plano claro, com metas realistas.","continua →"),
  ("Etapa 2","Corrigir e reabilitar","Cada fase tem seu cuidado; a fisioterapia e a reabilitação caminham junto com a parte cirúrgica.","continua →"),
  ("Etapa 3","Acompanhar de perto","Casos complexos pedem retornos e ajustes ao longo do tempo — o acompanhamento é parte do tratamento.","quase lá →"),
  ("Guarde isso","Tratamento de etapas, de perto","Salve e compartilhe.","Amanhã: quando vale uma segunda opinião. →")],
 [("SAB · Quando procurar","Segunda opinião: quando vale","Fim de semana em família. Quando buscar um segundo olhar faz diferença.","deslize →"),
  ("Quando 1","Antes de uma decisão grande","Diante de uma cirurgia importante ou de um caso difícil, um segundo olhar tranquiliza e às vezes abre opções.","continua →"),
  ("Quando 2","Quando algo não fecha","Se o diagnóstico ou o plano não fazem sentido para você, perguntar é um direito, não uma ofensa.","continua →"),
  ("O cuidado","Leve seus exames","Levar a história e os exames que já tem torna a segunda opinião mais útil e rápida.","quase lá →"),
  ("Guarde isso","Perguntar é cuidar","Salve e compartilhe.","Amanhã, o fecho da temporada: como eu penso o cuidado. →")],
 [("DOM · Como eu penso","Como eu penso o cuidado","Fechando a Semana dos Casos Complexos — e a nossa temporada. O que guia o meu trabalho.","deslize →"),
  ("Princípio 1","Avaliação cuidadosa","Cada caso é único. Entender a história e a pessoa inteira vem antes de qualquer conduta.","continua →"),
  ("Princípio 2","Plano realista e honesto","Sem promessas. Explico o que dá para fazer, os riscos e os benefícios, e decidimos juntos.","continua →"),
  ("Princípio 3","Função em primeiro lugar","O foco é melhorar como a pessoa anda, se move e vive — nunca a estética.","quase lá →"),
  ("Converse comigo","Todo caso difícil merece um caminho","Avaliação cuidadosa e plano realista. WhatsApp na bio. Obrigado por acompanhar!","Na segunda, começa uma nova temporada. Até lá! →")],
]})
